examples/react/tsconfig.json

feat: add tsconfig.json for examples/react

---

packages/core/binding/index.d.ts

update type of PluginResolveHookParam

---

.changeset/lucky-papayas-sleep.md
crates/plugin_css/src/lib.rs
packages/runtime-plugin-hmr/src/hot-module-state.ts
packages/runtime/src/module-system.ts
packages/runtime/src/module.ts

fix: hmr does not remove css

---

.github/ISSUE_TEMPLATE/bug_report.yml

fix bug report templates in issues templates do not work

fix: Bug templates in issues templates do not work

---

examples/vue/package.json
pnpm-lock.yaml

Fix spelling errors in workspace words

fix: misspelling of words

---

js-plugins/vue/tsconfig.json

epeatedly build vue-plugin package be error

fix: js-plugins/vue repeat build error

---

scripts/build.mjs

bootstrap script add build vue plugin command

feat: script add command to build vue-plugins

---

.github/workflows/lint.yaml
.github/workflows/release.yaml
.github/workflows/rust-build.yaml
.github/workflows/rust-plugin-build.yaml
.github/workflows/ts-test.yaml
package.json

chore: limit pnpm version to 7

---

packages/create-farm/README.md

Feat: Create farm/readme

---

README.md
packages/create-farm/index.ts
packages/create-farm/package.json
packages/create-farm/tsconfig.json
packages/create-farm/utils/packageManager.ts
pnpm-lock.yaml

- update readme 
- fix type error with `create-farm` package

chore: update readme

---

.changeset/long-lamps-dream.md
examples/react/farm.config.ts
examples/react/package.json
examples/react/src/index.scss
examples/react/src/index.tsx
js-plugins/sass/.eslintrc.json
js-plugins/sass/README-zh-CN.md
js-plugins/sass/README.md
js-plugins/sass/package.json
js-plugins/sass/src/index.ts
js-plugins/sass/src/options.ts
js-plugins/sass/tsconfig.build.json
js-plugins/sass/tsconfig.json
pnpm-lock.yaml

feat: support scss compile

---

.changeset/happy-bags-listen.md
cspell.json
examples/vue/package.json
examples/vue/src/Main.vue
js-plugins/vue/package.json
js-plugins/vue/src/farm-vue-hmr.ts
js-plugins/vue/src/farm-vue-plugin.ts
js-plugins/vue/src/farm-vue-types.ts
js-plugins/vue/src/generatorCode.ts
js-plugins/vue/src/utils.ts
packages/core/binding/binding.d.ts
pnpm-lock.yaml

- feat(js-plugins/vue): support more css preprocessors
- fix(js-plugins/vue): dynamic import for preprocessors
Support `less/sass/stylus` for `@farmfe/js-plugin-vue`, now you can use `less/sass/stylus` in Vue SFC.
As `@farmfe/js-plugin-vue`'s peer dependencies, please ensure that `less/sass/stylus` was installed in your project.
None of breaking changes.
None of related issues.

feat: support less/sass/stylus for @farmfe/js-plugin-vue

---

package.json
scripts/build.mjs

script dynamic-building package

chore(script): script dynamic-building package

---

js-plugins/vue/src/farm-vue-hmr.ts
js-plugins/vue/src/farm-vue-plugin.ts
js-plugins/vue/src/farm-vue-types.ts
js-plugins/vue/src/generatorCode.ts
js-plugins/vue/src/utils.ts

- update vue plugin of options
- none
- none

feat: update vue-options

---

js-plugins/vue/src/utils.ts

Using `unknown` instead of `any`, and using type predicates getting more helpful abilities with type guard.
None.
None.

fix: type declaration of utils func in `@farmfe/js-plugin-vue`

---

.changeset/shiny-pens-remember.md
Cargo.lock
crates/compiler/Cargo.toml
crates/compiler/src/lib.rs
crates/plugin_json/Cargo.toml
crates/plugin_json/src/lib.rs
crates/plugin_json/tests/fixtures/load/load.json
crates/plugin_json/tests/fixtures/transform/contain_comment.json
crates/plugin_json/tests/fixtures/transform/transform.json
crates/plugin_json/tests/load.rs
crates/plugin_json/tests/transform.rs

support compile .json
No
close #120

feat: support parse json file

---

.changeset/shiny-pens-remember.md
Cargo.lock
crates/compiler/Cargo.toml
crates/compiler/src/lib.rs
crates/plugin_json/Cargo.toml
crates/plugin_json/src/lib.rs
crates/plugin_json/tests/fixtures/load/load.json
crates/plugin_json/tests/fixtures/transform/contain_comment.json
crates/plugin_json/tests/fixtures/transform/transform.json
crates/plugin_json/tests/load.rs
crates/plugin_json/tests/transform.rs
js-plugins/vue/src/utils.ts

Optimize code style in utils function.
None.
None.

chore: pref code style in `@farmfe/js-plugin-vue`

---

scripts/build.mjs
scripts/logger.mjs

add new logger color log function

chore: Optimize script log output

---

.github/workflows/rust-test.yaml
crates/compiler/tests/update.rs

fix: coverage ci

---

crates/compiler/src/build/mod.rs
examples/react/farm.config.ts

Temporarily optimize input error log
original error handling
now error handling
Next,  the details of various logs way please see #171 .
Temporarily solve the current error message processing

chore: Optimization process error message

---

.changeset/seven-yaks-dress.md
packages/create-farm/templates/react/package.json
packages/create-farm/templates/vue/package.json

Modify template version of farm from * to latest to temporarily prevent errors in versions above pnpm8

chore(create-farm): Compatible with pnpm8

---

rust-plugins/sass/package.json

Currently, the npm packages under each system are not released correctly.

chore: prepublishOnly

---

cspell.json
scripts/build.mjs

feat(script): bootstrap add  write check protobuf environment

---

cspell.json
scripts/build.mjs

dont import exec package cause `pnpm bootstrap` doesn't work

fix: import exec error 

---

crates/plugin_resolve/src/resolver.rs

Resolve some border issues that were not resolved.
1.  `..` Equivalent to `../` should be a relative path
2.  main fields can be a file or directory. eg: `main: "./lib"`
3.  `@antd-design/icon-svg` not resolved

fix: resolve  error

---

.github/ISSUE_TEMPLATE/bug_report.yml

When the user raises a bug, it is convenient for the user to provide the necessary system information, as well as the version of the `@farmfe/core` package

chore: easy access to user system information

---

packages/core/package.json
scripts/build.mjs

- change build command 
```ts
"build": "rm -rf dist && tsc -p tsconfig.build.json",
```
Prevent tsconfig incremental settin, cause build error
- optimize code , add linux with mac prompt user logger

chore: Optimize installation code logic

---

CONTRIBUTING.md
CONTRIBUTING.zh-CN.md
ROADMAP.zh-CN.md
cspell.json

chore: update contribution.md

---

crates/compiler/src/update/diff_and_patch_module_graph.rs
crates/compiler/tests/fixtures/tree_shake/empty_specifiers/output.js
crates/compiler/tests/fixtures/tree_shake/html_entry/basic/output.js
crates/core/src/config/mod.rs
crates/plugin_resolve/src/lib.rs
crates/plugin_script/src/lib.rs
crates/plugin_tree_shake/src/lib.rs
crates/plugin_tree_shake/src/module.rs
crates/plugin_tree_shake/src/remove_useless_stmts.rs
crates/plugin_tree_shake/src/statement_graph.rs
crates/plugin_tree_shake/src/statement_graph/analyze_imports_and_exports.rs
crates/plugin_tree_shake/src/statement_graph/analyze_imports_and_exports/test.rs
crates/plugin_tree_shake/src/statement_graph/defined_idents_collector.rs
crates/plugin_tree_shake/src/statement_graph/used_idents_collector.rs
crates/plugin_tree_shake/tests/remove_useless_stmts.rs
crates/plugin_tree_shake/tests/statement_graph.rs
crates/plugin_tree_shake/tests/tree_shake_module.rs
crates/toolkit/src/hash/mod.rs
examples/script-entry/farm.config.js
examples/vue/farm.config.ts
packages/core/src/config/index.ts

```ts
// support following syntax in tree shake:
export const [a, b] = c; // export pattern decl
const [a, b] = c; // normal pattern decl
```

chore: support ident pat for tree shaking

---

.changeset/slow-moons-decide.md
crates/compiler/tests/common/mod.rs
crates/compiler/tests/fixtures/tree_shake/basic/output.js
crates/compiler/tests/fixtures/tree_shake/changed_ast/output.js
crates/compiler/tests/fixtures/tree_shake/cyclic_deps/output.js
crates/compiler/tests/fixtures/tree_shake/dynamic-import/output.js
crates/compiler/tests/fixtures/tree_shake/empty_specifier_export_all/output.js
crates/compiler/tests/fixtures/tree_shake/empty_specifiers/output.js
crates/compiler/tests/fixtures/tree_shake/export_all/output.js
crates/compiler/tests/fixtures/tree_shake/farm_config/output.js
crates/compiler/tests/fixtures/tree_shake/self-executed/output.js
crates/compiler/tests/tree_shake.rs
crates/plugin_runtime/src/lib.rs
crates/plugin_script/src/lib.rs

entry key as resource name
close #202

feat entry key as resource name

---

crates/utils/src/lib.rs

After today's clone, I happened to find that there are no test cases for the reactive method in the utils under crites, so I added it. I want to gradually read the project source code and participate in it

feat:add test for crate utils

---

examples/react-antd/package.json
examples/react/package.json
pnpm-lock.yaml

fix: examples dep version

---

.changeset/rotten-cooks-compare.md
crates/compiler/tests/common/mod.rs
crates/compiler/tests/fixtures/tree_shake/basic/output.js
crates/compiler/tests/fixtures/tree_shake/cyclic_deps/output.js
crates/compiler/tests/fixtures/tree_shake/dynamic-import/output.js
crates/compiler/tests/fixtures/tree_shake/empty_specifier_export_all/output.js
crates/compiler/tests/fixtures/tree_shake/empty_specifiers/output.js
crates/compiler/tests/fixtures/tree_shake/farm_config/output.js
crates/compiler/tests/fixtures/tree_shake/html_entry/basic/output.js
crates/compiler/tests/fixtures/tree_shake/non_script/index.css
crates/compiler/tests/fixtures/tree_shake/non_script/index.ts
crates/compiler/tests/fixtures/tree_shake/non_script/output.js
crates/compiler/tests/fixtures/tree_shake/self-executed/output.js
crates/plugin_tree_shake/src/lib.rs

fix: tree shake should ignore shake non-script modules

---

examples/script-entry/CHANGELOG.md
examples/script-entry/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/runtime-plugin-hmr/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
pnpm-lock.yaml

chore: bump version

---

crates/plugin_resolve/src/resolver.rs
crates/plugin_resolve/tests/fixtures/resolve-node-modules/normal/node_modules/dir-main/package.json
crates/plugin_resolve/tests/mod.rs
examples/script-entry/CHANGELOG.md
examples/script-entry/package.json
packages/core/CHANGELOG.md
packages/core/package.json

chore: support resolve .. and absolute dir

---

.github/workflows/lint.yaml
.github/workflows/release.yaml
.github/workflows/rust-build.yaml
.github/workflows/rust-plugin-build.yaml
.github/workflows/rust-test.yaml
.github/workflows/ts-test.yaml
package.json
pnpm-lock.yaml

chore: upgrade pnpm version

---

.npmrc
js-plugins/vue/package.json
pnpm-lock.yaml

fix: disable autoinstall peers

---

.changeset/lazy-crabs-confess.md
packages/create-farm/templates/react/farm.config.ts
packages/create-farm/templates/react/package.json
packages/create-farm/templates/react/src/index.tsx
packages/create-farm/templates/react/tsconfig.json
packages/create-farm/templates/vue/.eslintrc.json
packages/create-farm/templates/vue/CHANGELOG.md
packages/create-farm/templates/vue/farm.config.ts
packages/create-farm/templates/vue/src/env.d.ts

chore: update template

---

.changeset/spotty-clouds-speak.md
crates/compiler/tests/fixtures/tree_shake/basic/output.js
crates/compiler/tests/fixtures/tree_shake/changed_ast/output.js
crates/compiler/tests/fixtures/tree_shake/cyclic_deps/output.js
crates/compiler/tests/fixtures/tree_shake/dynamic-import/output.js
crates/compiler/tests/fixtures/tree_shake/empty_specifier_export_all/output.js
crates/compiler/tests/fixtures/tree_shake/empty_specifiers/output.js
crates/compiler/tests/fixtures/tree_shake/export_all/output.js
crates/compiler/tests/fixtures/tree_shake/farm_config/output.js
crates/compiler/tests/fixtures/tree_shake/non_script/output.js
crates/compiler/tests/fixtures/tree_shake/self-executed/output.js
crates/core/src/context/mod.rs
crates/plugin_resolve/src/resolver.rs
crates/plugin_resolve/tests/browser.rs
crates/plugin_runtime/src/lib.rs
crates/plugin_script/src/lib.rs
packages/core/src/config/index.ts
packages/core/tests/js-plugins.spec.ts

chore: do not resolve browser when target env is node

---

crates/core/src/config/mod.rs
examples/react/farm.config.ts
packages/core/src/config/index.ts

fix: add default config for script

---

.changeset/metal-tigers-build.md
packages/create-farm/farm.config.mjs

- use minify and remove sourcemap file
size 1.22m -> 192kb

chore: create-farm remove sourcemap reduce size

---

packages/cli/package.json
packages/cli/src/utils.ts

feat: add log function

---

packages/create-farm/index.ts

As discussed on discord, this PR makes installing dependencies the default, but users can opt out with `--skip-install`.

feat: install dependencies by default

---

packages/cli/src/index.ts

feat: Listening for unknown command

---

.changeset/angry-rules-fly.md
packages/create-farm/templates/react/package.json

Temporarily solve the problem of react template failure

chore: update create-farm version

---

.changeset/lovely-avocados-sniff.md
packages/core/src/config/schema.ts

fix: examples vue fail to start

---

examples/react/src/index.scss
examples/react/src/variables.scss
rust-plugins/sass/src/lib.rs

```sass
@import './variables.scss';
body {
background-color: $primaryColor;
}
```
```shell
Error: Can't find stylesheet to import
````

fix: the import file is not found in sass

---

.changeset/tricky-rockets-exist.md
packages/create-farm/templates/react/package.json
packages/create-farm/templates/vue/package.json

update farm-core@0.6.4，At present, the only thing that can start is 0.6.4.

chore(create-farm): update version 

---

packages/create-farm/index.ts

Remove existing types (any type) @types/prompts

chore(create-farm): remove any type

---

crates/plugin_css/src/lib.rs
crates/plugin_runtime/src/insert_runtime_plugins.rs
examples/react-sass-js/package.json

fix: windows issue

---

.changeset/chatty-bananas-retire.md
packages/core/src/config/schema.ts
packages/create-farm/CHANGELOG.md
packages/create-farm/farm.config.mjs

fix(create-farm): build error with `presetEnv`

---

.changeset/seven-vans-march.md
examples/vue/package.json
packages/create-farm/templates/vue/package.json
pnpm-lock.yaml

chore: add vue template corejs deps resolve build error

---

.changeset/nervous-balloons-move.md
.github/workflows/rust-test.yaml
.github/workflows/ts-test.yaml
js-plugins/vue/src/farm-vue-hmr.ts
js-plugins/vue/src/farm-vue-plugin.ts
js-plugins/vue/src/generatorCode.ts
packages/create-farm/CHANGELOG.md
rust-plugins/react/src/lib.rs

fix: dev code presents in prod

---

crates/compiler/src/build/mod.rs
crates/compiler/src/update/mod.rs
crates/compiler/src/update/patch_module_group_graph.rs
crates/compiler/tests/fixtures/css/modules/composes/external_import/output.js
crates/core/Cargo.toml
crates/core/src/module/mod.rs
crates/core/src/module/module_graph.rs
crates/plugin_css/src/lib.rs

chore: make the modules order be execution order

---

crates/compiler/examples/react_update.rs
crates/compiler/src/update/mod.rs
crates/node/src/lib.rs
packages/core/binding/binding.d.ts
packages/core/src/compiler/index.ts

chore: support sync option when update

---

packages/cli/src/index.ts
packages/cli/src/utils.ts
packages/core/src/config/types.ts
packages/core/src/index.ts
packages/core/src/plugin/rustPluginResolver.ts
packages/core/src/server/hmr-engine.ts
packages/core/src/server/index.ts
packages/core/src/server/middlewares/lazy-compilation.ts
packages/core/src/server/middlewares/proxy.ts
packages/core/src/server/middlewares/resources.ts
packages/core/src/server/openBrowser.ts
packages/core/src/watcher/index.ts

chore(cli): optimize code

---

.changeset/lucky-rockets-behave.md
crates/plugin_css/src/lib.rs
examples/vue-antdv/.eslintrc.json
examples/vue-antdv/.gitignore
examples/vue-antdv/CHANGELOG.md
examples/vue-antdv/css.js
examples/vue-antdv/farm.config.ts
examples/vue-antdv/index.html
examples/vue-antdv/package.json
examples/vue-antdv/src/index.ts
examples/vue-antdv/src/main.vue
examples/vue-antdv/tsconfig.json
pnpm-lock.yaml

fix: css dev bugs and add antd vue examples

---

.changeset/cyan-singers-judge.md
packages/create-farm/templates/react/package.json
packages/create-farm/templates/vue/package.json

chore(create-farm): update template version

---

examples/lib-watch/farm.config.mjs
examples/lib-watch/index.ts
examples/lib-watch/package.json
examples/lib-watch/tsconfig.json
packages/core/src/index.ts
packages/core/src/watcher/index.ts
pnpm-lock.yaml

chore(core): optimize watcher code

---

examples/vue/farm.config.ts

fix: example syntax error

---

packages/core/src/server/middlewares/proxy.ts

chore: optimize proxy plugin

---

package.json

chore: update script

---

packages/core/src/compiler/index.ts
packages/core/src/watcher/index.ts

chore: support HMR error recovery

---

.github/workflows/coverage.yaml
.github/workflows/lint.yaml
.github/workflows/rust-build.yaml
.github/workflows/rust-plugin-build.yaml
.github/workflows/rust-test.yaml

chore: update test coverage

---

scripts/bootstrap.mjs
scripts/build.mjs
scripts/logger.mjs

chore: remove unless code

---

Cargo.lock
crates/compiler/Cargo.toml
crates/compiler/tests/css.rs
crates/core/src/lib.rs
crates/node/src/lib.rs
crates/plugin_tree_shake/Cargo.toml
crates/plugin_tree_shake/src/lib.rs
crates/plugin_tree_shake/src/module.rs
crates/plugin_tree_shake/src/remove_useless_stmts.rs
crates/plugin_tree_shake/src/statement_graph.rs
packages/core/package.json
packages/core/src/compiler/index.ts
packages/core/src/index.ts

Optimize tree shake perf

---

.changeset/hungry-jokes-exist.md
.changeset/wicked-tips-jump.md
README.md
README.zh-CN.md
crates/plugin_lazy_compilation/src/dynamic_module.ts
crates/plugin_script/src/lib.rs
crates/plugin_script/src/swc_plugins.rs
packages/create-farm/templates/react/package.json
packages/create-farm/templates/vue/package.json

fix: lazy compilation and deadlock

---

.changeset/funny-weeks-train.md
Cargo.lock
crates/compiler/src/build/parse.rs
crates/core/src/error/mod.rs
crates/plugin_script/Cargo.toml
crates/plugin_script/src/swc_plugins.rs
crates/toolkit/Cargo.toml
crates/toolkit/src/css/mod.rs
crates/toolkit/src/html/mod.rs
crates/toolkit/src/lib.rs
crates/toolkit/src/script/mod.rs

chore: pretty syntax error

---

.changeset/hip-dryers-build.md
packages/core/src/index.ts

fix: build public dir

---

.changeset/chilly-insects-sell.md
.changeset/forty-parrots-look.md
.changeset/forty-pugs-listen.md
crates/compiler/src/generate/render_resource_pots.rs
crates/compiler/src/lib.rs
crates/compiler/src/update/mod.rs
crates/compiler/src/update/regenerate_resources.rs
crates/compiler/tests/common/mod.rs
crates/core/src/config/config_regex.rs
crates/core/src/config/html.rs
crates/core/src/config/mod.rs
crates/core/src/config/preset_env.rs
crates/core/src/module/module_graph.rs
crates/core/src/plugin/mod.rs
crates/core/src/resource/resource_pot_map.rs
crates/node/src/plugin_adapters/js_plugin_adapter/thread_safe_js_plugin_hook.rs
crates/node/src/plugin_toolkit/swc_transforms.rs
crates/plugin_css/src/transform_resource_pot.rs
crates/plugin_html/src/lib.rs
crates/plugin_polyfill/src/lib.rs
crates/testing_helpers/src/lib.rs
crates/toolkit_plugin_types/src/swc_transforms.rs
examples/multi-page-app/farm.config.ts
examples/multi-page-app/src/pages/about/index.html
examples/multi-page-app/src/pages/base.html
examples/multi-page-app/src/pages/index/index.html
packages/core/binding/index.d.ts
packages/core/src/config/schema.ts
packages/core/tests/js-plugins.spec.ts
packages/runtime-plugin-hmr/src/hot-module-state.ts

close #377 
close #385 
close #386 
close #383

chore: add more features

---

.changeset/quick-carrots-cheer.md
crates/node/src/lib.rs
examples/multi-page-app/src/pages/about/index.tsx
examples/multi-page-app/src/pages/index/index.tsx
packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/server/middlewares/resources.ts

feat: support configure `server.spa`

---

js-plugins/less/README-zh-CH.md
js-plugins/less/README.md
js-plugins/less/package.json
js-plugins/less/src/options.ts
js-plugins/less/tsconfig.build.json
js-plugins/sass/README-zh-CN.md
js-plugins/sass/README.md
js-plugins/sass/package.json
js-plugins/sass/src/options.ts
js-plugins/sass/tsconfig.build.json

add the jump link between Chinese and English Readme and change the js-plugin name
None
None

style: add the jump link between Chinese and English Readme 

---

.changeset/fast-hotels-act.md
crates/compiler/src/update/diff_and_patch_module_graph.rs
crates/compiler/src/update/diff_and_patch_module_graph/test_diff_module_deps.rs
crates/compiler/src/update/diff_and_patch_module_graph/test_diff_module_graph.rs
crates/compiler/src/update/diff_and_patch_module_graph/test_patch_module_graph.rs
crates/compiler/src/update/mod.rs
crates/compiler/src/update/update_context.rs
examples/react-antd/package.json
examples/react-antd/src/antd-layout.tsx
examples/react-antd/src/main.tsx
pnpm-lock.yaml

fix: hmr remove dependency

---

.changeset/famous-bugs-worry.md
packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/watcher/index.ts

fix: wait write file to finish by default

---

.changeset/loud-pigs-sin.md
crates/compiler/src/generate/mod.rs
crates/compiler/src/update/mod.rs
crates/compiler/src/update/regenerate_resources.rs
crates/compiler/tests/fixtures/update/index.css
crates/compiler/tests/fixtures/update/index.ts
crates/compiler/tests/update.rs
crates/core/src/plugin/mod.rs
crates/core/src/plugin/plugin_driver.rs
crates/node/src/plugin_adapters/rust_plugin_adapter/mod.rs
crates/node/src/plugin_adapters/rust_plugin_adapter/plugin_loader.rs
crates/plugin_css/src/lib.rs
crates/plugin_css/src/transform_resource_pot.rs
crates/plugin_runtime/src/lib.rs
packages/core/src/index.ts

fix: css hmr will always reload the whole page

---

packages/core/src/server/middlewares/resources.ts
packages/core/src/utils/file.ts

support view output file structure
no
close https://github.com/farm-fe/farm/issues/269

feat: support view output file structure

---

.changeset/great-laws-flash.md
.gitignore
crates/compiler/src/build/mod.rs
crates/compiler/src/build/validate_config.rs
crates/plugin_resolve/src/lib.rs
crates/toolkit/src/fs/mod.rs
examples/react-antd/package.json
packages/core/src/config/env.ts
packages/core/src/config/index.ts
packages/core/src/index.ts
packages/core/tests/common.ts
pnpm-lock.yaml

fix: mode set to development when build

---

README.md

chore: update readme wechat

---

.changeset/purple-buses-divide.md
.changeset/tall-apricots-pretend.md
crates/compiler/src/update/diff_and_patch_module_graph.rs
crates/compiler/src/update/diff_and_patch_module_graph/test_diff_module_graph.rs
crates/compiler/src/update/patch_module_group_graph.rs
examples/css-modules/farm.config.ts
examples/css-modules/src/child.tsx
examples/css-modules/src/main.tsx
packages/core/src/config/index.ts
packages/core/src/server/index.ts
packages/runtime-plugin-hmr/src/hot-module-state.ts
packages/runtime-plugin-hmr/src/index.ts

fix: hmr patch

---

.changeset/empty-planets-smash.md
crates/plugin_html/src/lib.rs

chore: make resources order injected to html execution order

---

.changeset/forty-tables-nail.md
packages/core/src/server/middlewares/hmr.ts
packages/core/src/server/middlewares/lazy-compilation.ts

fix: hmr middleware return slowly

---

.changeset/good-bobcats-return.md
packages/core/src/server/hmr-engine.ts
packages/core/src/server/middlewares/hmr.ts
packages/runtime-plugin-hmr/src/index.ts
packages/runtime-plugin-hmr/src/types.ts

chore: remove hmr http request and use websocket/eval instead

---

.changeset/dull-hairs-judge.md
.github/workflows/rust-build.yaml
Cargo.lock
crates/node/Cargo.toml
crates/node/src/lib.rs
crates/plugin_script/src/handle_entry_resources.rs
cspell.json
packages/core/binding/binding.cjs
packages/core/binding/binding.d.ts
packages/core/binding/index.d.ts
packages/core/binding/index.js
packages/core/package.json
packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/server/middlewares/hmr.ts
packages/core/src/watcher/index.ts
pnpm-lock.yaml

feat: remove chokidar and add a rust file watcher

---

.github/workflows/coverage.yaml

chore(ci): we need more space

---

.changeset/curly-bananas-admire.md
.changeset/four-olives-kiss.md
ROADMAP.md
ROADMAP.zh-CN.md
js-plugins/vue/src/farm-vue-hmr.ts
js-plugins/vue/src/generatorCode.ts
packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/watcher/index.ts
packages/runtime-plugin-hmr/src/hot-module-state.ts

chore: await write finish

---

.changeset/twenty-cats-grab.md
crates/compiler/src/update/mod.rs
crates/core/src/context/mod.rs
crates/core/src/lib.rs
crates/core/src/module/mod.rs
crates/core/src/module/watch_graph.rs
crates/core/src/plugin/mod.rs
crates/node/src/lib.rs
examples/react/src/variables.scss
packages/core/binding/binding.d.ts
packages/core/src/compiler/index.ts
packages/core/src/index.ts
packages/core/src/plugin/index.ts
packages/core/src/server/index.ts
packages/core/src/watcher/index.ts
rust-plugins/sass/src/lib.rs

feat: support add extra watch file

---

.changeset/smooth-mugs-drop.md
.changeset/sour-dolphins-cough.md
crates/node/src/lib.rs
packages/core/binding/binding.d.ts
packages/core/src/compiler/index.ts
packages/core/src/config/schema.ts
packages/core/src/index.ts
packages/core/src/watcher/index.ts
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json
rust-plugins/sass/src/lib.rs

fix: extra watch files panic and dev server hook execution order

---

js-plugins/postcss/src/index.ts

FarmPostcssPlugin in production is not work
no
close https://github.com/farm-fe/farm/issues/491

fix: postcss plugin in production no work

---

README.md
README.zh-CN.md

Update Wechat Image

---

README.md
README.zh-CN.md
cspell.json

chore: add quick start video

---

README.md
README.zh-CN.md

chore: update contributors

---

.changeset/metal-balloons-dream.md
examples/vue/index.html
packages/create-farm/templates/vue/index.html

fix(create-farm): vue template production pnpm preview NODE_ENV undefined error

---

crates/core/src/plugin/mod.rs
crates/node/src/plugin_adapters/js_plugin_adapter/mod.rs
crates/node/src/plugin_adapters/js_plugin_adapter/thread_safe_js_plugin_hook.rs
examples/react/farm.config.ts
packages/core/src/plugin/index.ts

chore: js plugin support finish hook

---

js-plugins/less/package.json
js-plugins/less/src/index.ts
js-plugins/less/src/options.ts
js-plugins/less/src/utils.ts
js-plugins/less/tsconfig.build.json
js-plugins/postcss/package.json
js-plugins/postcss/src/index.ts
js-plugins/postcss/src/utils.ts
js-plugins/postcss/tsconfig.build.json
js-plugins/sass/package.json
js-plugins/sass/src/options.ts
js-plugins/sass/tsconfig.build.json
package.json
packages/core/package.json

- Format the ts production
- Add the clean script 
- Add the watchFile for the less @import
None
None

feat: format the ts production && add the clean script && add the watchFile for the less @import

---

js-plugins/dts/src/context.ts
packages/core/src/utils/logger.ts

chore: expand other properties of logger

---

packages/core/src/index.ts
packages/core/src/server/index.ts

An initial attempt to resolve port conflict when starting multiple servers at the same time (#519)
Temporarily achieved by running an HTTP server to check port availability before normalizing the configs
Current behavior: dev server will start on port 9000 by default, and the following servers on port 9001, 9002... The hmr port will also ++ at the same time.
close #288 

feat: enable port auto-increment to prevent port conflict (#519)

---

examples/react/farm.config.ts
packages/core/src/config/schema.ts
packages/core/src/server/index.ts

chore: Optimize http error callback handling and server host properties

---

.changeset/bright-suits-shave.md
crates/compiler/src/build/mod.rs
crates/compiler/src/generate/render_resource_pots.rs
crates/core/src/config/mod.rs
crates/plugin_css/src/lib.rs
crates/plugin_css/src/transform_resource_pot.rs
crates/plugin_script/src/lib.rs
crates/toolkit/src/css/mod.rs
crates/toolkit/src/sourcemap/swc_gen.rs
cspell.json
examples/react/src/components/card/index.tsx
examples/react/src/original-sourcemap/config.d.ts
examples/react/src/original-sourcemap/config.js
examples/react/src/original-sourcemap/config.js.map
scripts/build.mjs
tsconfig.base.json

feat support sourcemap chain based on swc sourcemap

---

.changeset/blue-files-learn.md
js-plugins/dts/package.json
js-plugins/less/package.json
js-plugins/postcss/package.json
js-plugins/sass/package.json
js-plugins/solid/farm.config.mjs
js-plugins/solid/package.json
js-plugins/vue/package.json
package.json
packages/core/package.json
scripts/build.mjs
scripts/clean.mjs

1. Modify the root package configuration file.
2. Modify solid plugins publish file remove source map.
3. Remove npm publish file with js plugins. like sourcemap  Specify publish file
4. Decoupled clean script method.
5. Optimize the time of clean method.
6. Clear all build directories before bootstrap

chore: optimize script

---

.changeset/young-bees-matter.md
crates/plugin_css/src/lib.rs
examples/react-antd/farm.config.ts
examples/react-antd/src/main.css
examples/react-antd/src/main.tsx
packages/core/binding/index.d.ts
packages/core/src/compiler/index.ts
packages/core/src/config/index.ts
packages/core/src/config/schema.ts
packages/core/src/config/types.ts
packages/core/src/index.ts
packages/core/src/server/hmr-engine.ts
packages/core/src/server/index.ts
packages/core/src/server/middlewares/resources.ts

feat: support write to disk

---

CONTRIBUTING.zh-CN.md

CONTRIBUTING.zh-CN.md running command error
`cd Examples/Reaction&&pnpm start`

chore: CONTRIBUTING.zh-CN.md running command error

---

packages/core/src/server/index.ts

#538 
**Description:Multiple farm projects run port conflicts at  same time**
**BREAKING CHANGE:No, only one function has been modified.**
**Related issue (if exists):Solve the problem of multiple farm project start port conflicts**

Solve the problem of multiple farm project start port conflicts

---

packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/server/index.ts
packages/core/src/server/middlewares/resources.ts

publicPath adapted to the relative path
None
None

fix: publicPath adapted to the relative path

---

packages/core/src/config/index.ts
packages/core/src/server/index.ts

Avoid userConfig.server being undefined
None
None

avoid userConfig.server being undefined 

---

examples/react-antd/farm.config.ts
examples/react/farm.config.ts
packages/core/src/config/index.ts
packages/core/src/server/index.ts
packages/core/tests/config.spec.ts

chore: add host config and solve the problem of multiple execution of server

---

.changeset/serious-files-impress.md
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json

chore: update template version

---

.changeset/warm-dots-heal.md

chore: bump version in plugin hmr

---

examples/react-antd/farm.config.ts
examples/react-antd/src/antd-layout.tsx
examples/react/farm.config.ts
examples/vue-antdv/farm.config.ts
examples/vue-antdv/src/main.vue
packages/core/src/config/index.ts
packages/core/src/config/schema.ts
packages/core/src/config/types.ts
packages/core/src/server/index.ts
packages/core/src/server/middlewares/headers.ts

e.g often needs to set request headers or micro-front-end projects for local debugging.

feat: add server headers

---

.changeset/fifty-tigers-doubt.md
Cargo.lock
crates/core/Cargo.toml
crates/macro_cache_item/Cargo.toml
crates/toolkit_plugin_types/Cargo.toml
crates/utils/Cargo.toml

chore: version bump

---

.changeset/flat-emus-search.md
crates/plugin_static_assets/src/lib.rs
js-plugins/less/CHANGELOG.md

fix: static assets loading issue when public path is empty

---

packages/core/src/config/index.ts
packages/core/src/utils/share.ts
pnpm-lock.yaml

feat: support jsplugin array format

---

.changeset/green-trains-crash.md
crates/core/src/plugin/mod.rs
crates/core/src/resource/mod.rs
crates/node/src/plugin_adapters/js_plugin_adapter/mod.rs
crates/node/src/plugin_adapters/js_plugin_adapter/thread_safe_js_plugin_hook.rs
examples/react/farm.config.ts
packages/core/src/plugin/index.ts
packages/core/tests/js-plugins.spec.ts

chore: support buildStart, buildEnd, updateModules js plugins hook

---

.changeset/warm-camels-film.md
examples/react/farm.config-test.ts
examples/react/farm.config.ts
examples/vue/config/test2.config.ts
examples/vue/test.config.ts
packages/cli/src/index.ts
packages/cli/src/types.ts
packages/cli/src/utils.ts

fix: remove cli resolve unless options

---

packages/core/CHANGELOG.md
packages/create-farm/CHANGELOG.md

fix: spell issue

---

.changeset/tasty-forks-help.md
js-plugins/sass/src/options.ts
packages/core/src/watcher/index.ts

Fix the `const __require = createRequire(xxx);` code
None
None

fix: change the createModule code

---

examples/public-path/farm.config.ts
packages/core/src/index.ts

fix: public path reoslve undefined error 

---

.changeset/chatty-points-marry.md
.changeset/cyan-dolphins-tease.md
examples/react/farm.config.ts
examples/vue/farm.config.ts
packages/cli/src/index.ts
packages/core/src/server/index.ts
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json

fix: strictPort listen error 

---

.changeset/swift-flies-cheer.md
crates/compiler/src/build/mod.rs
crates/core/src/context/log_store.rs
crates/core/src/context/mod.rs
crates/core/src/resource/mod.rs
crates/node/src/lib.rs
crates/node/src/plugin_adapters/js_plugin_adapter/context.rs
examples/react/farm.config.ts
packages/core/src/plugin/index.ts

feat: Support js plugin hook context methods for unplugin

---

packages/core/binding/index.d.ts
packages/core/src/plugin/index.ts

chore: export hook context type

---

.changeset/hip-seals-sip.md
packages/core/src/config/index.ts
packages/core/src/server/index.ts

Format the normalizePublicPath function.
None
None

fix: format the normalizePublicPath function

---

.changeset/quick-swans-approve.md
js-plugins/less/src/index.ts
js-plugins/postcss/src/index.ts
js-plugins/sass/src/index.ts

1. Fix watchfile problems in less production environment.
2. Integrate userconfig

fix: less plugins build watchfile error

---

.changeset/many-glasses-cough.md
examples/vue-antdv/package.json
examples/vue-jsx/package.json
examples/vue/package.json
examples/vue/src/components/Button.vue
examples/vue/src/components/Card.vue
js-plugins/vue/farm.config.mjs
js-plugins/vue/package.json
js-plugins/vue/src/farm-vue-plugin.ts
js-plugins/vue/src/generatorCode.ts
pnpm-lock.yaml

fix css variable does not work as expected

---

js-plugins/solid/package.json
js-plugins/vue/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/server/middlewares/resources.ts
packages/runtime/CHANGELOG.md
packages/runtime/package.json
pnpm-lock.yaml

fix: dev server read file error

---

packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/index.ts
packages/core/src/watcher/index.ts
packages/core/tests/config.spec.ts
pnpm-lock.yaml

fix: in production conflict server fn with command

---

.changeset/seven-moose-sin.md
.changeset/thirty-timers-peel.md
crates/compiler/src/update/diff_and_patch_module_graph.rs
crates/compiler/src/update/diff_and_patch_module_graph/test_diff_module_deps.rs
crates/compiler/src/update/diff_and_patch_module_graph/test_diff_module_graph.rs
crates/compiler/src/update/diff_and_patch_module_graph/test_patch_module_graph.rs
crates/compiler/src/update/handle_update_modules.rs
crates/compiler/src/update/mod.rs
crates/compiler/src/update/patch_module_group_graph.rs
crates/compiler/src/update/patch_module_group_graph/tests.rs
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json

fix: HMR update fail when there are deep dependencies changed

---

.changeset/sour-crabs-share.md
crates/compiler/tests/fixtures/tree_shake/issue_625/dep-index.js
crates/compiler/tests/fixtures/tree_shake/issue_625/dep.js
crates/compiler/tests/fixtures/tree_shake/issue_625/index.ts
crates/compiler/tests/fixtures/tree_shake/issue_625/output.js
crates/compiler/tests/fixtures/tree_shake/issue_625/register.js
crates/plugin_css/src/lib.rs
crates/plugin_script/src/lib.rs
crates/plugin_tree_shake/src/lib.rs
crates/plugin_tree_shake/src/module.rs
crates/plugin_tree_shake/src/remove_useless_stmts.rs
crates/plugin_tree_shake/src/statement_graph.rs
crates/plugin_tree_shake/tests/remove_useless_stmts.rs
packages/core/src/plugin/js/farm-to-vite-context.ts
packages/core/src/plugin/js/utils.ts
packages/core/src/plugin/js/vite-plugin-adapter.ts

Fix tree-shake self-executed module issue && vite plugin adapterissue

---

packages/create-farm/CHANGELOG.md
packages/create-farm/package.json
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json

chore: bump version for farm core in create farm

---

scripts/build.mjs

fix: ExcludePlugin variable define error

---

README.md
README.zh-CN.md

update: readme.md

---

packages/core/src/config/index.ts

fix: resolveServerConflict judge error

---

.changeset/few-buckets-approve.md
crates/compiler/tests/fixtures/partial_bundling/basic/output.js
crates/compiler/tests/fixtures/tree_shake/cyclic_deps/output.js
crates/compiler/tests/fixtures/tree_shake/empty_specifier_export_all/output.js
crates/compiler/tests/fixtures/tree_shake/empty_specifiers/output.js
crates/compiler/tests/fixtures/tree_shake/farm_config/output.js
crates/compiler/tests/fixtures/tree_shake/issue_625/output.js
crates/plugin_script/src/handle_entry_resources.rs
crates/plugin_static_assets/src/lib.rs
examples/script-entry/farm.config.mjs
examples/script-entry/index.ts
examples/script-entry/test.mjs

fix: issue #652

---

js-plugins/less/CHANGELOG.md
js-plugins/less/package.json
js-plugins/less/src/index.ts

fix: incorrect filters of transform hook of js plugin less

---

rust-plugins/sass/CHANGELOG.md
rust-plugins/sass/package.json
rust-plugins/sass/src/lib.rs

fix: #660 incorrect default path resolve for default sass embedded binary

---

.changeset/calm-berries-rescue.md
.changeset/few-lizards-move.md
.github/workflows/test-examples.yaml
README.md
README.zh-CN.md
crates/compiler/tests/fixtures/tree_shake/cyclic_deps/output.js
crates/compiler/tests/fixtures/tree_shake/issue_625/output.js
crates/plugin_script/src/handle_entry_resources.rs
examples/vite-adapter-solid/farm.config.ts
examples/vite-adapter-vue/farm.config.ts
examples/vue-jsx/farm.config.mjs
examples/x-data-spreadsheet/farm.config.ts
js-plugins/less/src/index.ts
js-plugins/less/src/utils.ts
js-plugins/postcss/src/index.ts
js-plugins/sass/src/index.ts
js-plugins/sass/src/options.ts
js-plugins/svgr/src/index.ts
scripts/build.mjs
scripts/test-examples.mjs

chore: normalzie js plugins options

---

.changeset/three-windows-report.md
examples/arco-pro/farm.config.ts
examples/react-antd/farm.config.ts
examples/vue/farm.config.ts
js-plugins/less/src/index.ts
pnpm-lock.yaml

fix: less watchFile server undefined before restart server

---

.github/workflows/release.yaml
.github/workflows/test-examples.yaml
rust-plugins/react/CHANGELOG.md
rust-plugins/react/package.json
rust-plugins/sass/CHANGELOG.md
rust-plugins/sass/package.json

chore: bump version for react and sass

---

js-plugins/vue/CHANGELOG.md
js-plugins/vue/package.json

chore: bump version for js plugin vue

---

README.md
README.zh-CN.md
examples/generate-dts/CHANGELOG.md
examples/generate-dts/package.json
examples/script-entry/CHANGELOG.md
examples/script-entry/package.json
js-plugins/solid/package.json
js-plugins/vue/package.json
packages/core/CHANGELOG.md
packages/core/README.md
packages/core/package.json

chore: bump version for #704

---

crates/core/src/plugin/plugin_driver.rs
crates/core/src/record/mod.rs
crates/node/src/lib.rs
js-plugins/record-viewer/src/client/src/components/TransformRecord.vue
packages/core/binding/binding.d.ts

- resolve record add is hmr filed
- transform record add is hmr filed
- record manager add trigger filed
No

refactor: record  add hmr flag

---

crates/core/src/plugin/plugin_driver.rs
crates/core/src/record/mod.rs
crates/node/src/lib.rs

Fix the issue where config.record does not work in the transform hook
no

fix: config record not work in transform hook

---

.changeset/dry-points-help.md
README.md
README.zh-CN.md
cspell.json
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json

chore: update readme bump template version

---

.github/workflows/release.yaml
.github/workflows/rust-build.yaml
.github/workflows/rust-plugin-build.yaml
.github/workflows/rust-plugin-react-ci.yaml
.github/workflows/rust-plugin-sass-ci.yaml
packages/core/npm/linux-arm64-gnu/README.md
packages/core/npm/linux-arm64-gnu/package.json
packages/core/npm/linux-arm64-musl/README.md
packages/core/npm/linux-arm64-musl/package.json
packages/core/package.json
rust-plugins/react/npm/linux-arm64-gnu/README.md
rust-plugins/react/npm/linux-arm64-gnu/package.json
rust-plugins/react/npm/linux-arm64-musl/README.md
rust-plugins/react/npm/linux-arm64-musl/package.json
rust-plugins/react/package.json
rust-plugins/react/scripts/copy-artifacts.mjs
rust-plugins/sass/npm/linux-arm64-gnu/README.md
rust-plugins/sass/npm/linux-arm64-gnu/package.json
rust-plugins/sass/npm/linux-arm64-musl/README.md
rust-plugins/sass/npm/linux-arm64-musl/package.json
rust-plugins/sass/package.json
rust-plugins/sass/scripts/copy-artifacts.mjs

Add Linux ARM64 support.
All builds have passed. See [this link](https://github.com/rhyzx/farm/actions/runs/6904194415).
N/A

build: linux arm64 support

---

packages/create-farm/CHANGELOG.md
packages/create-farm/package.json
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/farm.config.ts
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/farm.config.ts
packages/create-farm/templates/vue/package.json

chore(create-farm): update dependencies

---

.changeset/brown-starfishes-lick.md
crates/plugin_script/src/handle_entry_resources.rs
examples/script-entry/farm.config.mjs
examples/script-entry/package.json
packages/core/src/config/types.ts

fix: runtime resource panic

---

rust-plugins/react/index.js
rust-plugins/sass/index.js

**Description:** Native plugins(react/sass) still not working on linux arm64, due to the absence of resolving logic for that platform.
**BREAKING CHANGE:** N/A
**Related issue (if exists):** N/A

fix: linux arm64 native plugin resolving

---

.changeset/quiet-games-raise.md

chore: add changeset

---

.changeset/early-timers-sell.md
packages/core/package.json

fix: core cjs

---

.changeset/early-timers-sell.md
.changeset/thick-ghosts-happen.md
crates/compiler/src/build/module_cache.rs
crates/compiler/tests/fixtures/partial_bundling/basic/output.js
crates/compiler/tests/fixtures/script/import_equals/output.js
crates/compiler/tests/fixtures/tree_shake/farm_config/output.js
crates/core/src/cache/cache_store.rs
crates/core/src/cache/module_cache.rs
crates/plugin_runtime/src/handle_entry_resources.rs
crates/plugin_runtime/src/lib.rs
crates/plugin_script/src/lib.rs
crates/toolkit/src/common.rs
examples/script-entry/farm.config.cjs.ts
examples/script-entry/farm.config.ts
examples/script-entry/package.json
examples/script-entry/test-cjs.cjs
js-plugins/solid/package.json
js-plugins/vue/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/core/src/config/types.ts
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
packages/runtime/src/module-system.ts
packages/runtime/src/resource-loader.ts
pnpm-lock.yaml

fix: issue 747

---

rust-plugins/react/scripts/copy-artifacts.mjs
rust-plugins/sass/scripts/copy-artifacts.mjs

chore: update rust plugins scripts

---

.changeset/olive-apples-fly.md
packages/create-farm/templates/solid/index.html

chore: bump version fix solid template build error

---

.changeset/heavy-pans-greet.md
.changeset/thirty-rabbits-sell.md
crates/compiler/src/build/module_cache.rs
crates/compiler/src/generate/finalize_resources.rs
crates/compiler/src/update/mod.rs
crates/core/src/cache/cache_store.rs
crates/core/src/cache/module_cache.rs
crates/core/src/context/mod.rs
crates/core/src/module/watch_graph.rs
crates/node/src/lib.rs
crates/node/src/plugin_adapters/js_plugin_adapter/context.rs
crates/plugin_static_assets/src/lib.rs
examples/css-modules/src/main.module.scss
examples/css-modules/src/variables.scss
examples/vite-adapter-vue/src/components/code.js
rust-plugins/sass/src/lib.rs

fix #760 #761

---

packages/cli/src/index.ts
packages/core/src/config/index.ts
packages/core/src/config/schema.ts
packages/core/src/config/types.ts
packages/core/src/index.ts
packages/core/src/watcher/index.ts
packages/core/tests/binding.spec.ts
packages/core/tests/common.ts
pnpm-lock.yaml

chore: support env mode

---

examples/react/farm.config.ts
packages/core/src/index.ts
packages/core/src/server/index.ts
packages/core/src/utils/build.ts
packages/core/src/utils/color.ts
packages/core/src/utils/logger.ts
packages/core/src/watcher/index.ts
pnpm-lock.yaml

chore: optimize server logger with cli style

---

.changeset/soft-cows-check.md
packages/cli/src/index.ts
packages/core/src/config/index.ts

chore: bump @farmfe/cli version

---

.changeset/red-pumas-return.md
packages/core/src/config/index.ts

fix: import config cache

---

.changeset/tough-brooms-smash.md
.github/workflows/test-examples.yaml
.github/workflows/ts-test.yaml
crates/node/src/lib.rs
packages/core/src/compiler/index.ts
packages/core/src/config/index.ts
packages/core/src/config/normalize-config/normalize-persistent-cache.ts
packages/core/src/watcher/index.ts
packages/core/tests/config.spec.ts

fix: #774 again

---

.changeset/selfish-lobsters-work.md
Cargo.lock
crates/compiler/src/build/mod.rs
crates/compiler/src/build/module_cache.rs
crates/compiler/src/update/mod.rs
crates/core/Cargo.toml
crates/core/src/cache/cache_store.rs
crates/core/src/cache/module_cache.rs
crates/core/src/cache/module_cache/immutable_modules.rs
crates/core/src/cache/module_cache/mutable_modules.rs
crates/macro_cache_item/Cargo.toml
crates/macro_cache_item/src/lib.rs
crates/plugin_css/Cargo.toml
crates/plugin_css/src/transform_css_to_script.rs
crates/plugin_resolve/src/resolver.rs
crates/toolkit_plugin_types/Cargo.toml
crates/utils/Cargo.toml
packages/core/src/config/index.ts
packages/core/src/config/normalize-config/normalize-persistent-cache.ts

chore(persistent-cache): optimize cache

---

crates/compiler/src/build/mod.rs
crates/compiler/src/build/module_cache.rs
crates/compiler/src/update/module_cache.rs
crates/core/src/cache/module_cache.rs
crates/core/src/cache/module_cache/immutable_modules.rs
crates/core/src/cache/module_cache/module_memory_store.rs
crates/core/src/cache/module_cache/mutable_modules.rs

chore: optimize cache 2

---

crates/compiler/src/build/mod.rs
crates/core/src/cache/resource_cache/resource_pot.rs
examples/react/farm.config.ts
examples/react/src/components/welcome/index.tsx
examples/react/src/main.tsx
packages/core/src/index.ts
packages/core/src/watcher/configWatcher.ts

chore: optimize cache 3

---

package.json

chore: build cjs when publish

---

.changeset/healthy-plums-lick.md
.changeset/tall-foxes-brush.md
examples/react/farm.config.ts
examples/react/package.json
packages/cli/src/index.ts
packages/core/src/index.ts
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/.npmrc
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/.npmrc
packages/create-farm/templates/vue/package.json

feat: add `farm clean` command

---

.changeset/twelve-kings-build.md
packages/core/src/plugin/index.ts
packages/core/src/plugin/type.ts

chore:  bump version for publishing addtional cpu arch package

---

.changeset/silly-trains-impress.md
Cargo.lock
crates/compiler/src/build/mod.rs
crates/compiler/src/build/module_cache.rs
crates/compiler/src/update/mod.rs
crates/core/Cargo.toml
crates/node/Cargo.toml
crates/node/src/lib.rs
packages/core/package.json

chore: optimize cache 4

---

.changeset/weak-dancers-film.md
packages/core/src/utils/build.ts
packages/core/src/utils/color.ts
packages/core/src/utils/logger.ts
packages/create-farm/CHANGELOG.md
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json

chore: update logger info provide custom color

---

.github/workflows/ci.yaml
crates/compiler/tests/css.rs
crates/compiler/tests/fixtures/css/url_replacer/absolute/index.css
crates/compiler/tests/fixtures/css/url_replacer/absolute/index.ts
crates/compiler/tests/fixtures/css/url_replacer/absolute/output.js
crates/compiler/tests/fixtures/css/url_replacer/ignored/index.css
crates/compiler/tests/fixtures/css/url_replacer/ignored/index.ts
crates/compiler/tests/fixtures/css/url_replacer/ignored/output.js
crates/plugin_css/src/source_replacer.rs

fix: css url asset

---

.changeset/hungry-rockets-know.md
crates/compiler/src/generate/partial_bundling.rs
crates/compiler/src/update/regenerate_resources/generate_and_diff_resource_pots.rs
crates/plugin_partial_bundling/src/generate_module_pots.rs
crates/plugin_partial_bundling/src/merge_module_pots.rs

fix: enforceTargetMinSize panic

---

.github/ISSUE_TEMPLATE/bug_report.yml

chore: update issues template

---

packages/core/src/config/index.ts
packages/core/src/plugin/index.ts

chore: add server options in configResolved & remove unless code

---

examples/build-lib-external/farm.config.ts
examples/build-lib-external/index.js
examples/build-lib-external/index.ts
examples/build-lib-external/package.json
examples/vite-adapter-vue/farm.config.ts
packages/core/src/config/index.ts
packages/core/src/utils/logger.ts
packages/core/src/utils/share.ts
pnpm-lock.yaml

chore: auto detect node external and automatically find entry files

---

packages/core/src/config/index.ts
packages/create-farm/farm.config.ts

chore: Optimize the trigger time of vite adaptation

---

crates/compiler/src/build/mod.rs
packages/core/src/utils/build.ts
packages/core/src/utils/color.ts
packages/core/src/utils/logger.ts

1. refactor logger All methods are changed to the default pass string
2. utils All color properties are exported by default
3. fix error remove process exit All error operations are handed over to node

fix: error logging and remove process exit

---

examples/react/farm.config.ts
packages/core/src/index.ts
packages/core/src/server/middlewares/resources.ts
packages/core/src/utils/build.ts
packages/core/src/utils/color.ts
packages/core/src/utils/share.ts
packages/core/src/utils/trace-dependencies.ts

chore: optimize code

---

examples/react/farm.config.ts
examples/react/src/index.tsx
examples/react/src/main.tsx
examples/react/src/typings.d.ts
packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/index.ts
packages/core/src/server/hmr-engine.ts

fix: merge cli server config error

---

CONTRIBUTING.zh-CN.md
js-plugins/dts/src/index.ts

Change options to optional.
None.
None.

fix(js-plugins/dts): change options to optional

---

.changeset/lazy-maps-happen.md

chore: bump minor version for all packages

---

examples/build-lib-external/package.json
examples/resolve-module-graph/package.json
examples/server-proxy/package.json
js-plugins/dts/package.json

chore: update examples package.json

---

.changeset/calm-spies-peel.md
packages/core/src/config/index.ts

chore: make vite plugins execute later

---

.changeset/quiet-mugs-burn.md
packages/core/src/plugin/js/farm-to-vite-config.ts
packages/core/src/server/index.ts
packages/core/src/server/middlewares/cors.ts
packages/core/src/server/middlewares/headers.ts
packages/core/src/server/middlewares/proxy.ts
packages/core/src/server/middlewares/resources.ts

fix: dev server random 503

---

examples/react-antd/farm.config.ts
examples/react-antd/package.json
examples/react-antd/src/antd-layout.tsx
packages/core/src/server/middlewares/proxy.ts
packages/core/src/server/middlewares/resources.ts
pnpm-lock.yaml

chore: optimize proxy error

---

.changeset/cool-pianos-tell.md
crates/compiler/src/lib.rs
crates/compiler/src/update/mod.rs
crates/node/src/plugin_adapters/js_plugin_adapter/hooks/mod.rs
crates/node/src/plugin_adapters/js_plugin_adapter/hooks/transform_html.rs
crates/node/src/plugin_adapters/js_plugin_adapter/mod.rs
crates/plugin_html/src/lib.rs
crates/plugin_script/src/lib.rs
examples/vite-adapter-vue/farm.config.ts
examples/vite-adapter-vue/package.json
examples/vite-adapter-vue/src/index.ts
examples/vite-adapter-vue/src/pages/index.vue
examples/vite-adapter-vue/svg-component-global.d.ts
examples/vite-adapter-vue/svg-component.d.ts
packages/core/src/compiler/index.ts
packages/core/src/plugin/js/vite-plugin-adapter.ts
packages/core/src/plugin/type.ts
packages/core/src/server/index.ts
pnpm-lock.yaml

Fix transformIndexHtml does not work as expected

---

.changeset/hip-news-cheer.md
.changeset/smooth-zebras-stare.md
.github/workflows/ci.yaml
crates/compiler/tests/fixtures/script/import_equals/output.js
crates/plugin_runtime/src/lib.rs
crates/plugin_runtime/src/render_resource_pot/mod.rs
crates/plugin_runtime/src/render_resource_pot/source_replacer.rs
examples/vite-adapter-vue/components.d.ts
examples/vite-adapter-vue/src/pages/about.vue
packages/core/CHANGELOG.md
packages/core/src/plugin/js/farm-to-vite-config.ts
packages/create-farm/CHANGELOG.md
packages/create-farm/farm.config.ts
packages/runtime/src/module-system.ts

fix: failed to load external cjs require when output esm

---

.changeset/mean-ducks-confess.md
ROADMAP.md
ROADMAP.zh-CN.md
crates/compiler/src/build/mod.rs
crates/plugin_static_assets/src/lib.rs
crates/utils/src/lib.rs
cspell.json
packages/core/binding/index.d.ts
packages/core/src/compiler/index.ts
packages/core/src/config/index.ts
packages/core/src/config/normalize-config/normalize-external.ts
packages/core/src/config/schema.ts
packages/core/src/plugin/js/apply-html-transform.ts
packages/core/src/plugin/js/farm-to-vite-config.ts
packages/core/src/plugin/js/vite-plugin-adapter.ts
packages/create-farm/farm.config.ts
rust-plugins/sass/src/lib.rs

fix: vite migrate bugs

---

crates/plugin_static_assets/src/lib.rs
packages/core/src/server/middlewares/resources.ts

chore: preserve query and hash for static assets

---

packages/runtime-plugin-hmr/src/hmr-client.ts
packages/runtime-plugin-hmr/src/hot-module-state.ts
packages/runtime-plugin-hmr/src/logger.ts
packages/runtime/src/module-system.ts

chore: use verbose level log with development

---

.changeset/famous-numbers-think.md
packages/runtime-plugin-import-meta/src/index.ts

fix: `import.meta.url` contain id is `undefined`

---

.changeset/famous-moose-wave.md
examples/react/src/main.tsx
packages/create-farm/index.ts

chore: create-farm autoInstall default false

---

.changeset/tough-falcons-confess.md
crates/compiler/src/lib.rs
crates/plugin_html/src/deps_analyzer.rs
crates/plugin_html/src/lib.rs
crates/plugin_html/src/resources_injector.rs
crates/plugin_html/src/utils.rs
crates/plugin_html/tests/mod.rs
examples/vite-adapter-vue/components.d.ts
examples/vite-adapter-vue/index.html
examples/vite-adapter-vue/public/global.js
examples/vite-adapter-vue/src/components/HelloWorld.vue

chore: support absolute path for script tag

---

Cargo.lock
crates/compiler/Cargo.toml
crates/compiler/src/lib.rs
crates/core/src/config/mod.rs
crates/plugin_progress/Cargo.toml
crates/plugin_progress/src/lib.rs
cspell.json
packages/core/binding/index.d.ts
packages/core/src/config/index.ts
packages/core/src/config/schema.ts
packages/core/src/utils/trace-dependencies.ts

Add a progress bar to display compilation progress
1. add rust plugin progress
2. config add progress options
3. enable the progress plugin by default
4. progress plugin is disabled by default when reading config and tracking dependencies
https://github.com/farm-fe/farm/assets/24955673/322280c6-33b3-4fd9-8272-b3ab339964f2
no
close https://github.com/farm-fe/farm/issues/717

feat: add progress plugin

---

.changeset/hungry-students-repair.md
packages/core/src/plugin/js/farm-to-vite-config.ts

fix: default minify to false in prod when using vite plugins

---

crates/core/Cargo.toml
package.json
packages/plugin-tools/CHANGELOG.md
packages/plugin-tools/farm.config.ts
packages/plugin-tools/package.json
packages/plugin-tools/src/copy-artifacts.ts
packages/plugin-tools/src/index.ts

fix: copy artifacts

---

packages/core/tests/common.ts
packages/plugin-tools/CHANGELOG.md
packages/plugin-tools/package.json
packages/plugin-tools/src/copy-artifacts.ts

fix: plugin tools log

---

.changeset/fresh-books-guess.md
.changeset/heavy-hats-bathe.md
crates/plugin_define/src/lib.rs
crates/plugin_resolve/src/resolver.rs
crates/plugin_resolve/tests/fixtures/resolve-node-modules/issue-983/node_modules/bn.js/lib/bn.js
crates/plugin_resolve/tests/fixtures/resolve-node-modules/issue-983/node_modules/bn.js/package.json
crates/plugin_resolve/tests/mod.rs
examples/env/farm.config.mjs
examples/env/index.html
packages/core/src/config/index.ts
packages/core/tests/config.spec.ts

fix: 982 983

---

README.md
README.zh-CN.md
cspell.json

docs(README): add graphs contributors

---

examples/arco-pro/farm.config.ts
packages/core/src/config/index.ts
packages/core/tests/config.spec.ts

fix: modify env `FARM_HMR_BASE` not undefined

---

.changeset/tasty-doors-shop.md
packages/create-farm/templates/lit/package.json
packages/create-farm/templates/preact/package.json
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/svelte/package.json
packages/create-farm/templates/vanilla/package.json
packages/create-farm/templates/vue/package.json

chore: bump template version

---

.changeset/pre.json
crates/utils/src/lib.rs

chore: release 1.0 stable

---

examples/decorators/package.json
examples/vite-adapter-svelte/package.json
examples/vite-adapter-vue-sfc-src/package.json
packages/cli/CHANGELOG.md
packages/cli/package.json
packages/create-farm/CHANGELOG.md
packages/create-farm/package.json
packages/create-farm/templates/lit/package.json
packages/create-farm/templates/preact/package.json
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/svelte/package.json
packages/create-farm/templates/vanilla/package.json
packages/create-farm/templates/vue/package.json
pnpm-lock.yaml

chore: bump cli to 1.0

---

crates/plugin_resolve/src/resolver.rs
crates/plugin_resolve/src/resolver/utils.rs

chore(resolver): optimize resolve error message

---

.changeset/chatty-pants-refuse.md
crates/node/src/plugin_adapters/rust_plugin_adapter/plugin_loader.rs
packages/core/farm.config.ts
packages/create-farm-plugin/templates/rust/.github/workflows/build.yaml
packages/create-farm-plugin/templates/rust/.github/workflows/ci.yaml
packages/create-farm-plugin/templates/rust/.github/workflows/release.yml
packages/create-farm-plugin/templates/rust/.gitignore

chore: update rust plugin template

---

examples/react/farm.config.ts
packages/cli/src/index.ts
packages/core/farm.config.ts
packages/core/package.json
packages/core/src/utils/share.ts
packages/core/tests/cjs.spec.ts

chore: remove emit node experimental warning

---

Cargo.lock
crates/core/Cargo.toml
crates/core/src/common/mod.rs
crates/core/src/lib.rs
crates/swc_transformer_import_glob/src/lib.rs
crates/swc_transformer_import_glob/tests/fixtures/default_glob_parent/dir/bar.js
crates/swc_transformer_import_glob/tests/fixtures/default_glob_parent/dir/foo.js
crates/swc_transformer_import_glob/tests/fixtures/default_glob_parent/src/input.expected.js
crates/swc_transformer_import_glob/tests/fixtures/default_glob_parent/src/input.js
crates/swc_transformer_import_glob/tests/fixtures/glob_embrace/dir/bar.js
crates/swc_transformer_import_glob/tests/fixtures/glob_embrace/dir/bar.mjs
crates/swc_transformer_import_glob/tests/fixtures/glob_embrace/dir/foo.cjs
crates/swc_transformer_import_glob/tests/fixtures/glob_embrace/dir/foo.js
crates/swc_transformer_import_glob/tests/fixtures/glob_embrace/input.expected.js
crates/swc_transformer_import_glob/tests/fixtures/glob_embrace/input.js
crates/swc_transformer_import_glob/tests/mod.rs
crates/testing_helpers/src/lib.rs

chore: support glob brace

---

js-plugins/solid/package.json
packages/core/src/server/index.ts

fix: hmr Path windows parsing

---

.changeset/itchy-seas-vanish.md
packages/core/src/plugin/js/index.ts

fix: problems with the load filter not working

---

.changeset/six-grapes-flash.md
js-plugins/postcss/farm.config.mjs
js-plugins/postcss/src/index.ts

fix: postcss internal plugins

---

.changeset/cuddly-cobras-provide.md
packages/core/src/plugin/js/farm-to-vite-config.ts

chore: add prototype check

---

.changeset/famous-meals-impress.md
examples/vite-adapter-vue/farm.config.ts
examples/vite-adapter-vue/package.json
examples/vite-adapter-vue/src/pages/about.vue
packages/core/src/config/index.ts
packages/core/src/plugin/js/farm-to-vite-config.ts
pnpm-lock.yaml

fix: vite adapter config

---

crates/core/Cargo.toml
crates/toolkit/Cargo.toml

chore: lock swc version

---

.changeset/proud-toes-pump.md
rust-plugins/sass/src/lib.rs

chore: remove print

---

.changeset/blue-roses-add.md
crates/toolkit/src/html/mod.rs
crates/toolkit/src/minify/mod.rs
examples/react-ssr/farm.config.mjs
examples/react-ssr/index.html
examples/react-ssr/server.js

chore: less strict html parsing

---

.changeset/lemon-tomatoes-stare.md
packages/core/src/config/index.ts
packages/core/src/index.ts

fix: Inject the correct NODE_ENV when parsing the configuration file

---

.changeset/chilly-mirrors-grab.md
.changeset/cuddly-sloths-hammer.md
.changeset/curly-apes-sin.md
.changeset/tough-mayflies-rule.md
crates/compiler/src/lib.rs
crates/plugin_css/src/lib.rs
examples/sass/farm.config.ts
examples/sass/src/index.scss
examples/sass/src/style/dep.scss
examples/sass/src/style/variables.scss
examples/static-assets/farm.config.ts
examples/static-assets/package.json
examples/static-assets/src/style/dep/font.scss
examples/static-assets/src/style/dep/variables.scss
examples/static-assets/src/style/index.scss
examples/static-assets/src/style/is-plain-object.scss
js-plugins/sass/package.json
js-plugins/sass/src/index.ts
packages/core/src/config/index.ts
packages/core/src/config/normalize-config/normalize-persistent-cache.ts
packages/create-farm-plugin/templates/rust/package.json
pnpm-lock.yaml

fix: sass import sourcemap

---

.github/workflows/release.yaml

与https://github.com/farm-fe/farm/pull/1155 的补充
zhel这里只正常执行了三个 template 测试

ci: fix unexpected execution of test 'create-farm'

---

.changeset/blue-pigs-visit.md
crates/compiler/tests/fixtures/tree_shake_development/css/index.ts
crates/compiler/tests/fixtures/tree_shake_development/css/output.js
crates/compiler/tests/fixtures/tree_shake_development/css/style/a.css
crates/compiler/tests/fixtures/tree_shake_development/css/style/b.css
crates/compiler/tests/tree_shake.rs
crates/core/src/module/module_graph.rs
crates/plugin_css/src/source_replacer.rs
crates/plugin_css/src/transform_css_to_script.rs
crates/plugin_html/src/utils.rs
crates/plugin_runtime/src/handle_entry_resources.rs
crates/plugin_runtime/src/render_resource_pot/source_replacer.rs
crates/plugin_tree_shake/src/lib.rs
crates/plugin_tree_shake/src/remove_useless_stmts.rs
examples/lazy-compilation/farm.config.ts
examples/lazy-compilation/index.html
examples/lazy-compilation/package.json
examples/lazy-compilation/src/comp-data.ts
examples/lazy-compilation/src/comp1.ts
examples/lazy-compilation/src/comp2.ts
examples/lazy-compilation/src/comp3.ts
examples/lazy-compilation/src/data.ts
examples/lazy-compilation/src/index.ts
examples/react/src/enums/biz.ts
examples/react/src/enums/index.ts
examples/react/src/main.tsx
pnpm-lock.yaml

fix: lazy compile error when mixed import and dynamic import

---

.changeset/stale-worms-chew.md
crates/plugin_css/src/dep_analyzer.rs
crates/plugin_css/src/source_replacer.rs
crates/plugin_css/tests/analyze_deps.rs
examples/css-modules/src/dep.css
examples/css-modules/src/index.css
examples/css-modules/src/index.tsx

fix: css import url panic

---

.changeset/odd-shoes-warn.md
packages/core/src/server/hmr-engine.ts

fix: check if the path of hmr exists

---

.github/renovate.json5

chore: update renovate.json5

---

.changeset/five-bobcats-report.md
crates/plugin_css/src/lib.rs
crates/plugin_define/src/lib.rs
crates/plugin_html/src/lib.rs
crates/plugin_html/src/resources_injector.rs
crates/plugin_json/src/lib.rs
crates/plugin_json/tests/transform.rs
crates/plugin_resolve/src/resolver.rs
crates/plugin_runtime/src/lib.rs
crates/plugin_runtime/src/render_resource_pot/mod.rs
examples/less/farm.config.ts
examples/public-path/farm.config.ts
examples/react-sass-js/farm.config.ts
examples/sass-plugin-rust/farm.config.ts
examples/sass/farm.config.ts
js-plugins/sass/src/index.ts
packages/core/binding/index.d.ts
packages/core/src/config/index.ts
packages/core/src/config/normalize-config/normalize-persistent-cache.ts
packages/core/src/config/schema.ts
packages/core/src/index.ts
packages/core/src/plugin/js/vite-plugin-adapter.ts
packages/core/src/server/error.ts
packages/core/src/server/middlewares/lazy-compilation.ts
packages/core/src/watcher/index.ts
packages/core/tests/cjs.spec.ts
packages/core/tests/config.spec.ts

fix: vite migrations bugs

---

.github/workflows/ci.yaml
.github/workflows/lint.yaml
.github/workflows/rust-build.yaml
.github/workflows/rust-test.yaml
packages/create-farm-plugin/templates/rust/.github/workflows/build.yaml

chore: arduino/setup-protoc@v3 from v1

---

.changeset/moody-goats-confess.md
crates/plugin_runtime/src/render_resource_pot/mod.rs

fix: minify module filter use absolute path

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml

chore: update issues_templates

---

Cargo.lock
crates/macro_testing/Cargo.toml
js-plugins/sass/package.json

chore: add testing crate metadata

---

.changeset/healthy-penguins-check.md
packages/core/binding/index.d.ts
packages/core/package.json

before
```ts
defineConfig({
compilation: {
// type: any
minify: {}
}
})
```
after:
```ts
defineConfig({
compilation: {
// type: JsMinifyOptions
minify: {}
}
})
```

fix: publish cannot find type

---

.changeset/clean-cobras-happen.md
examples/env/farm.config.mjs
packages/core/src/config/index.ts

fix: load env file cause error

---

.changeset/moody-rocks-sparkle.md
crates/plugin_css/src/lib.rs
crates/plugin_runtime/src/render_resource_pot/render_module.rs
examples/arco-pro/farm.config.ts
packages/core/package.json

fix: minify not work

---

crates/create-farm-rs/Cargo.toml

chore: update create farm toml file

---

.changeset/few-tools-mix.md
Cargo.lock
packages/create-farm-node/Cargo.toml
pnpm-lock.yaml

chore: Bump create farm version

---

.changeset/itchy-badgers-play.md
.vscode/settings.json
packages/core/src/config/index.ts
packages/core/src/utils/logger.ts
packages/core/tests/config/index.spec.ts
pnpm-lock.yaml

- check config stage
```ts
import { start } from '@farmfe/core';
// empty configPath and complation.input
start({});
```

fix: check config stage

---

.changeset/sixty-ears-grin.md
.github/workflows/ci.yaml
.github/workflows/rust-build.yaml
Cargo.lock
packages/create-farm-node/Cargo.toml
packages/create-farm-node/index.js
packages/create-farm-node/npm/darwin-arm64/package.json
packages/create-farm-node/npm/darwin-x64/package.json
packages/create-farm-node/npm/linux-arm64-gnu/package.json
packages/create-farm-node/npm/linux-arm64-musl/package.json
packages/create-farm-node/npm/linux-x64-gnu/package.json
packages/create-farm-node/npm/linux-x64-musl/package.json
packages/create-farm-node/npm/win32-arm64-msvc/package.json
packages/create-farm-node/npm/win32-ia32-msvc/package.json
packages/create-farm-node/npm/win32-x64-msvc/package.json
packages/create-farm-node/package.json

chore: bump create-farm-node version

---

.changeset/old-trees-guess.md
.github/workflows/release.yaml
packages/create-farm-node/create-farm.js

chore: update create-farm-node ci

---

.changeset/olive-mice-rush.md
.github/workflows/release.yaml
packages/create-farm-node/create-farm.js

chore: update ci

---

.changeset/wild-ears-check.md
examples/multi-page-app/e2e.spec.ts
examples/public-path/e2e.spec.ts
examples/public-path/public/test.js
packages/core/src/server/middlewares/resources.ts
packages/core/src/server/middlewares/static.ts

- failed fetch resource 
```tsx
import image from "./foo.png?url";
// before, server response html（faillback index.html）
// after, server response static file
```
- preview cannot response httml when multiple html
fix #1364

feat: failed fetch resource when with query or hash

---

.changeset/green-kings-fail.md
crates/plugin_resolve/src/resolver.rs
crates/plugin_resolve/tests/exports.rs
crates/plugin_resolve/tests/fixtures/resolve-node-modules/exports/node_modules/@issues/1433/lib/default.js
crates/plugin_resolve/tests/fixtures/resolve-node-modules/exports/node_modules/@issues/1433/package.json
e2e/default.spec.ts
examples/issues1433/farm.config.ts
examples/issues1433/index.js
examples/issues1433/package.json
pnpm-lock.yaml

fix: resolver priority issue

---

.changeset/rude-rockets-travel.md
crates/plugin_lazy_compilation/src/dynamic_module.ts

fix: 1418 lazy + minify error

---

.changeset/gentle-games-turn.md
examples/vite-adapter-vue/farm.config.ts
examples/vite-adapter-vue/package.json
examples/vite-adapter-vue/src/pages/index.vue
packages/core/src/index.ts
packages/core/src/server/index.ts
pnpm-lock.yaml

fix: 1432 files out of root does not be watched

---

.changeset/purple-flies-cheer.md
crates/core/src/module/mod.rs
crates/toolkit/src/script/mod.rs
packages/core/src/config/constants.ts
packages/core/src/config/index.ts
packages/core/src/utils/trace-dependencies.ts

before:
farm.config.cts // build error
after:
farm.config.cts // build success

fix: support mts/cts ext and fix traceDependencies use directory

---

.changeset/funny-eggs-arrive.md
js-plugins/solid/package.json
js-plugins/vue/package.json
packages/core/CHANGELOG.md
packages/core/package.json
pnpm-lock.yaml

fix: put http-proxy into production dependency

---

crates/compiler/Cargo.toml

chore: update crates version

---

Cargo.lock
crates/core/Cargo.toml

chore: update crates deps

---

.changeset/swift-windows-appear.md
packages/core/binding/binding.d.ts
packages/create-farm-plugin/templates/rust/Cargo.lock
packages/create-farm-plugin/templates/rust/playground/farm.config.ts
packages/create-farm-plugin/templates/rust/playground/package.json

chore: update rust plugin lock

---

.changeset/healthy-clouds-wave.md
examples/vite-adapter-vue2/farm.config.ts
packages/core/src/server/ws.ts

fix: proxy ws error

---

.changeset/short-pears-teach.md
crates/plugin_css/src/lib.rs
examples/less/src/index.less
examples/less/src/style/strip.less
packages/core/binding/binding.cjs
packages/core/binding/binding.d.ts

fix: css @import starting with ~

---

.changeset/itchy-news-occur.md
packages/core/src/server/index.ts
packages/core/src/server/middlewares/proxy.ts

fix: http2 not support http-proxy :path options

---

.changeset/polite-waves-rest.md
crates/plugin_bundle/src/lib.rs
crates/plugin_minify/src/imports_minifier.rs
crates/plugin_minify/src/lib.rs
crates/plugin_runtime/src/handle_entry_resources.rs
crates/plugin_runtime/src/lib.rs
examples/react-antd/farm.config.ts
examples/script-entry/farm.config.cjs.ts
examples/script-entry/farm.config.ts
js-plugins/dts/package.json
packages/core/src/config/normalize-config/normalize-output.ts
packages/core/src/config/schema.ts
packages/core/src/types/binding.ts
packages/core/src/utils/share.ts

feat: support single library bundle

---

.changeset/old-poets-kick.md
examples/vanilla-extract/package.json
packages/runtime-plugin-hmr/src/hmr-client.ts

fix: mpa hmr

---

.changeset/perfect-pandas-confess.md
crates/compiler/src/lib.rs
crates/compiler/src/trace_module_graph.rs
crates/node/src/lib.rs
packages/core/binding/binding.d.ts
packages/core/src/compiler/index.ts

feat: support compiler.traceModuleGraph

---

examples/refactor-react/farm.config.ts
packages/core/src/config/index.ts
packages/core/src/config/mergeConfig.ts

chore: optimize core logic

---

.changeset/tricky-jobs-sneeze.md
crates/core/src/config/mod.rs
crates/node/src/lib.rs
crates/plugin_bundle/src/lib.rs
crates/plugin_resolve/src/resolver.rs
crates/plugin_resolve/src/resolver/exports.rs
crates/plugin_runtime/src/lib.rs
crates/plugin_static_assets/src/lib.rs
examples/css-modules/farm.config.ts
examples/lib-for-browser/farm.config.ts
examples/script-entry/farm.config.cjs.ts
examples/script-entry/farm.config.ts
packages/cli/package.json
packages/core/binding/binding.d.ts
packages/core/package.json
packages/core/src/config/normalize-config/normalize-output.ts
packages/core/src/config/schema.ts
packages/core/src/index.ts
packages/core/src/types/binding.ts
packages/core/src/utils/trace-dependencies.ts
packages/core/src/watcher/index.ts
pnpm-lock.yaml

feat: support targetEnv library library-browser/node

---

.changeset/twenty-hotels-refuse.md
biome.json
packages/runtime-plugin-hmr/src/hmr-client.ts

fix: do not full reload when boundary module is not found

---

README.md
README.zh-CN.md

chore: update qrcode

---

examples/refactor-react/package.json
packages/cli/README.md
packages/cli/package.json
packages/cli/src/index.ts
packages/cli/src/types.ts
packages/cli/src/utils.ts
packages/core/src/config/constants.ts
packages/core/src/config/index.ts
pnpm-lock.yaml

chore: Completed all refactoring of @farmfe/cli

---

.changeset/shiny-dogs-lick.md
bench/benches/example.bench.ts
biome.json
crates/plugin_lazy_compilation/src/dynamic_module.ts
examples/lazy-compilation/farm.config.ts
js-plugins/sass/src/index.ts
package.json
packages/core/src/config/index.ts
packages/core/src/config/normalize-config/normalize-output.ts
packages/core/src/config/schema.ts
packages/core/src/config/types.ts
packages/core/src/index.ts
packages/core/src/server/middlewares/lazy-compilation.ts
packages/core/src/server/middlewares/resources.ts
packages/core/src/types/binding.ts
packages/core/src/types/swc-config.ts
packages/core/tests/cjs.spec.ts
packages/core/tests/config.spec.ts
pnpm-lock.yaml

fix: lazy compile url

---

.changeset/great-rice-lick.md
crates/compiler/tests/bundle.rs
crates/compiler/tests/fixtures/bundle/library/external/importNamespace/a.ts
crates/compiler/tests/fixtures/bundle/library/external/importNamespace/b.ts
crates/compiler/tests/fixtures/bundle/library/external/importNamespace/config.cjs.json
crates/compiler/tests/fixtures/bundle/library/external/importNamespace/config.json
crates/compiler/tests/fixtures/bundle/library/external/importNamespace/index.ts
crates/compiler/tests/fixtures/bundle/library/external/importNamespace/output.cjs.js
crates/compiler/tests/fixtures/bundle/library/external/importNamespace/output.js
crates/compiler/tests/fixtures/bundle/library/external/importNamespace/output.json.js
crates/compiler/tests/fixtures/bundle/library/hybrid/importCjsNamespace/a.ts
crates/compiler/tests/fixtures/bundle/library/hybrid/importCjsNamespace/b.ts
crates/compiler/tests/fixtures/bundle/library/hybrid/importCjsNamespace/config.cjs.json
crates/compiler/tests/fixtures/bundle/library/hybrid/importCjsNamespace/index.ts
crates/compiler/tests/fixtures/bundle/library/hybrid/importCjsNamespace/lodash.ts
crates/compiler/tests/fixtures/bundle/library/hybrid/importCjsNamespace/output.cjs.js
crates/compiler/tests/fixtures/runtime/bundle/cjs/normal/output.js
crates/plugin_bundle/src/resource_pot_to_bundle/bundle/bundle_analyzer.rs
crates/plugin_bundle/src/resource_pot_to_bundle/bundle/bundle_variable.rs
crates/plugin_bundle/src/resource_pot_to_bundle/targets/esm/generate.rs

```ts
// a.ts
import lodash from 'lodash';
console.log(lodash);
// b.ts
import * as lodash from 'lodash';
console.log(lodash)
// index.ts
import "./a.ts"
import "./b.ts"
const lodash = 123;
// output Error
lodash uniq failed
```

fix: bundle import namespace name uniq

---

examples/refactor-react/farm.config.ts
examples/vite-adapter-vue/svg-component.d.ts
packages/core/src/config/index.ts
packages/core/src/config/mergeConfig.ts
packages/core/src/server/index.ts

chore: perf resolve server options

---

packages/core/src/index.ts
packages/core/src/newServer/http.ts
packages/core/src/newServer/index.ts

refactor: delay the creation of the entire compiler to resolve port conflicts

---

crates/create-farm-rs/templates/vanilla/README.md

- A minor vanilla template title update in README

chore(create-farm): update README for vanilla template

---

.changeset/plenty-dodos-begin.md
examples/react/farm.config.js
packages/core/src/server/index.ts
packages/core/src/server/middlewares/hmrPing.ts
packages/core/src/server/middlewares/proxy.ts

fix: Setting ws in proxy causes an infinite loop

---

Cargo.lock
crates/bench/Cargo.toml
examples/vue-nativeui/package.json

fix: deps version

---

.changeset/angry-poets-complain.md

chore: bump runtime

---

.changeset/mighty-hairs-warn.md
.changeset/thick-bats-provide.md
crates/compiler/tests/fixtures/script/import_meta_url_with_URL/absolute_public_path/lit_str/output.js
crates/compiler/tests/fixtures/script/import_meta_url_with_URL/relative_public_path/tip/complate/output.js
crates/compiler/tests/fixtures/script/import_meta_url_with_URL/relative_public_path/tip/normal/output.js
crates/compiler/tests/fixtures/script/import_meta_url_with_URL/relative_public_path/tip/tip_star_star/output.js
crates/plugin_static_assets/src/lib.rs
js-plugins/dts/src/context.ts

chore: remove `query_string` when `emit_file` to `resource_map` in `plugin_static_assets`

---

.changeset/soft-buses-invent.md
crates/core/src/module/mod.rs
crates/plugin_polyfill/src/lib.rs
crates/toolkit/src/script/mod.rs

- module system analyze
- improve preset_env module path match 

fix: preset_env plugin match and module system `analyze`

---

.changeset/young-frogs-grab.md
crates/plugin_polyfill/src/lib.rs

- revert preset-env match
- add enforce exclude for preset-env match

fix: revert preset-env match & add enforce exclude

---

.changeset/empty-parents-cross.md
crates/core/src/config/custom.rs
crates/plugin_resolve/src/lib.rs
crates/plugin_resolve/src/resolver.rs
crates/plugin_resolve/src/resolver/utils.rs
cspell.json
packages/core/src/config/constants.ts
packages/core/src/config/index.ts
packages/core/src/config/normalize-config/normalize-resolve.ts
packages/core/src/config/schema.ts
packages/core/src/config/types.ts
packages/core/src/index.ts
packages/core/src/plugin/js/farm-to-vite-config.ts
packages/core/src/plugin/js/utils.ts
packages/core/src/types/binding.ts

feat: support resolve dedupe

---

.changeset/eighty-tomatoes-tap.md
packages/core/src/compiler/index.ts
rust-plugins/react/src/is_react_refresh_boundary.ts

fix: class component cannot hot update

---

.changeset/smooth-flowers-wink.md

chore: bump core version

---

.changeset/early-eyes-check.md

chore: bump runtime version

---

.changeset/hip-shoes-fix.md
packages/create-farm-plugin/templates/js/gitignore
packages/create-farm-plugin/templates/js/package.json

fix: 修复 js-plugin 模版配置问题

---

.changeset/afraid-lies-refuse.md
packages/cli/src/index.ts
packages/cli/src/types.ts
packages/core/src/config/mergeConfig.ts

feat(cli): support the configuration of `timeUnit`

feat(cli): support the configuration of `timeUnit`

---

.changeset/clean-drinks-tease.md
js-plugins/visualizer/src/client/src/pages/analysis/Plugin.vue

Optimize filters for Plugin Analysis 
None
None

fix: optimize filters for Plugin Analysis

---

.changeset/cuddly-gorillas-tell.md
.changeset/hot-humans-begin.md
.changeset/red-fans-notice.md
crates/compiler/src/build/mod.rs
crates/compiler/src/update/mod.rs
crates/compiler/src/update/regenerate_resources/mod.rs
crates/core/src/cache/cache_store.rs
examples/arcgis/farm.config.ts
examples/vite-adapter-vue/farm.config.ts
js-plugins/postcss/src/index.ts
js-plugins/visualizer/src/client/src/http.ts
js-plugins/visualizer/src/client/src/pages/analysis/Plugin.vue

fix: lazy compilation cache && postcss tailwind does not work on windows

---

bench/CHANGELOG.md
bench/package.json
js-plugins/solid/package.json
js-plugins/vue/package.json
packages/core/CHANGELOG.md
packages/core/package.json
packages/runtime/CHANGELOG.md
packages/runtime/package.json
pnpm-lock.yaml

chore: bump version. related issue #1775

---

.changeset/three-cats-collect.md
crates/compiler/tests/fixtures/bundle/library/hybrid/normal/output.js
crates/compiler/tests/fixtures/bundle/library/reexport/esm/namespace/index.ts
crates/compiler/tests/fixtures/bundle/library/reexport/esm/namespace/output.js
crates/plugin_bundle/src/resource_pot_to_bundle/defined_idents_collector.rs

```ts
// main.ts
import * as ns from "./path/to";
ns.default
// failed
ns.main_default
// expect
ns.default
```
fix #1805

fix: namespace import MemberProp name failed

---

.changeset/little-boats-watch.md
examples/react/farm.config.js
rust-plugins/react/src/lib.rs

fix(plugin-react): option useAbsoluatePath panic

---

.changeset/late-starfishes-help.md
crates/core/src/cache/cache_store.rs
crates/plugin_css/tests/fixtures/analyze_deps/basic.css
crates/toolkit/src/css/mod.rs
examples/tailwind/src/App.tsx
examples/vite-adapter-vue/src/App.vue

chore: revert change of replacing invalid css

---

.changeset/forty-penguins-melt.md
.vscode/settings.json
examples/refactor-react/src/main.tsx
packages/core/package.json
packages/core/src/server/middlewares/error.ts
packages/core/src/server/middlewares/index.ts
packages/runtime-plugin-hmr/package.json
pnpm-lock.yaml

fix(nightly): support node 16 downgraded execa version

---

packages/core/src/server/middlewares/resource.ts

fix(nightly): temporarily resolve spa reload issues

---

Cargo.lock
examples/refactor-react/farm.config.ts
packages/core/package.json
packages/core/src/config/index.ts
pnpm-lock.yaml
rust-plugins/replace-dirname/Cargo.toml
rust-plugins/replace-dirname/func.js
rust-plugins/replace-dirname/index.d.ts
rust-plugins/replace-dirname/index.js
rust-plugins/replace-dirname/package.json

feat(nightly): add `@farmfe/plugin-relace-dirname` rust plugin

---

package.json
pnpm-lock.yaml
scripts/build.mjs

chore(nightly): optimize scripts when start project

---

.changeset/selfish-goats-explode.md
crates/plugin_runtime/src/find_async_modules.rs

fix: async module detection wrong

---

package.json
scripts/build.mjs

fix(v2): build js plugins scirpts error

---

.changeset/happy-mice-visit.md
crates/compiler/tests/fixtures/runtime/bundle/lazy_compilation/config.json
crates/compiler/tests/fixtures/runtime/bundle/lazy_compilation/foo.ts
crates/compiler/tests/fixtures/runtime/bundle/lazy_compilation/output.js
crates/compiler/tests/fixtures/runtime/bundle/lazy_compilation/runtime.ts
crates/compiler/tests/runtime.rs
crates/core/src/plugin/mod.rs
crates/plugin_lazy_compilation/src/lib.rs
crates/plugin_runtime/src/lib.rs
crates/toolkit/src/script/constant.rs
crates/toolkit/src/script/mod.rs

…ntime & lazyCompilation conflict

fix: plugin circle call & dynamic import

---

packages/core/tsconfig.json

chore: ts lint

---

.changeset/clever-wasps-battle.md
examples/refactor-react/farm.config.ts
packages/core/src/config/env.ts
packages/core/src/config/index.ts

chore: export loadenv api

---

examples/refactor-react/farm.config.ts
packages/core/src/config/index.ts
packages/core/src/config/schema.ts
packages/core/src/config/types.ts
packages/core/src/server/index.ts
packages/core/src/watcher/index.ts

chore: redefine watch options

---

.github/workflows/rust-build.yaml
Cargo.lock
crates/core/Cargo.toml

fix: freebsd build & cargo publish

---

.changeset/eight-doors-matter.md
crates/compiler/tests/bundle.rs
crates/compiler/tests/fixtures/bundle/library/global_variable/config.json
crates/compiler/tests/fixtures/bundle/library/global_variable/index.ts
crates/compiler/tests/fixtures/bundle/library/global_variable/output.js
crates/compiler/tests/fixtures/bundle/library/global_variable/reexport.ts
crates/plugin_bundle/src/lib.rs
crates/plugin_bundle/src/resource_pot_to_bundle/bundle/mod.rs
crates/plugin_bundle/src/resource_pot_to_bundle/defined_idents_collector.rs
crates/plugin_bundle/src/resource_pot_to_bundle/mod.rs
crates/plugin_bundle/src/resource_pot_to_bundle/modules_analyzer/analyze.rs
crates/plugin_bundle/src/resource_pot_to_bundle/modules_analyzer/module_analyzer.rs
crates/plugin_bundle/src/resource_pot_to_bundle/targets/cjs/generate.rs
crates/plugin_bundle/src/resource_pot_to_bundle/targets/esm/generate.rs
crates/plugin_bundle/src/resource_pot_to_bundle/uniq_name.rs
packages/core/tests/cjs.spec.ts

fix: bundle global variable preserve

---

.changeset/fifty-poets-share.md
rust-plugins/react/package.json
rust-plugins/react/src/lib.rs

**Description:** 
- react plugin 执行优先级与swc 插件匹配
- ts->plugins->react
-  react plugin 优先级由100改变至99

fix(plugin-react): match swc priority

---

scripts/build.mjs

fix: bootstrap sort rust plugins error

---

.gitignore
scripts/build.mjs

chore: plugin-tools should be built before core.  And add an ignore for the idea config folder `.idea`

---

.changeset/honest-spoons-eat.md
.changeset/proud-dogs-help.md
crates/compiler/tests/fixtures/external/browser/normal/esm/output.js
crates/compiler/tests/fixtures/external/browser/object/esm/output.js
crates/compiler/tests/fixtures/partial_bundling/basic/output.js
crates/compiler/tests/fixtures/tree_shake/compiled-vue-comp/output.js
crates/compiler/tests/fixtures/tree_shake/farm_config/output.js
crates/compiler/tests/fixtures/tree_shake/import_namespace_partial/index.ts
crates/compiler/tests/fixtures/tree_shake/import_namespace_partial/output.js
crates/plugin_html/src/deps_analyzer.rs
crates/plugin_runtime/src/lib.rs
crates/plugin_tree_shake/src/statement_graph.rs
examples/external/index.html
examples/external/src/main.ts
examples/react/farm.config.js
examples/react/package.json
examples/react/src/main.tsx
pnpm-lock.yaml

fix: external alias #1957

---

.changeset/witty-plums-yawn.md
crates/compiler/tests/fixtures/bundle/library/hybrid/esm_export_cjs/output.cjs.js
crates/compiler/tests/fixtures/bundle/library/hybrid/esm_export_cjs/output.js
crates/compiler/tests/fixtures/bundle/library/hybrid/hybrid_entry_should_reexport/output.cjs.js
crates/compiler/tests/fixtures/bundle/library/hybrid/hybrid_entry_should_reexport/output.js
crates/plugin_bundle/src/resource_pot_to_bundle/bundle/bundle_analyzer.rs
crates/plugin_bundle/src/resource_pot_to_bundle/bundle/bundle_external.rs
crates/plugin_bundle/src/resource_pot_to_bundle/targets/cjs/generate.rs
crates/plugin_bundle/src/resource_pot_to_bundle/targets/esm/generate.rs

fix: cjs2esm entry omit default reexport

---

scripts/release.mjs

chore: update release scripts

---

examples/refactor-react/farm.config.ts
packages/core/src/server/index.ts
packages/core/src/utils/http.ts

chore: optimize server SIGTERM listener

---

.changeset/curvy-mangos-collect.md
packages/runtime-plugin-hmr/src/global.d.ts
packages/runtime-plugin-hmr/src/hmr-client.ts

fix: hmr.protocol does not work

---

.changeset/calm-apples-itch.md
.changeset/flat-gorillas-relax.md
.changeset/mean-garlics-cross.md
.changeset/purple-mice-drum.md
.changeset/tame-dragons-tap.md
crates/compiler/src/build/mod.rs
crates/compiler/src/build/module_cache.rs
crates/compiler/src/update/mod.rs
crates/compiler/src/update/regenerate_resources/generate_and_diff_resource_pots.rs
crates/core/src/cache/cache_store.rs
crates/core/src/cache/module_cache/mutable_modules.rs
crates/core/src/config/script.rs
crates/core/src/plugin/plugin_driver.rs
crates/plugin_html/src/lib.rs
crates/plugin_script/src/swc_script_transforms.rs
examples/vite-adapter-vue/src/App.vue
examples/vite-adapter-vue/src/index.ts
examples/vite-adapter-vue/src/pages/about.vue
examples/vite-adapter-vue/src/style.css
js-plugins/visualizer/src/client/src/pages/analysis/Compilation.vue
packages/core/src/config/index.ts
packages/core/src/config/schema.ts
packages/core/src/types/binding.ts
packages/core/tests/__snapshots__/cjs.spec.ts.snap
packages/core/tsconfig.build.json
packages/runtime-plugin-hmr/src/hmr-client.ts
packages/runtime-plugin-hmr/tsconfig.build.json
packages/runtime-plugin-import-meta/tsconfig.build.json
packages/runtime/tsconfig.build.json

feat: v1.5.0

---

README.md
README.zh-CN.md

chore: update qr code

---

examples/arco-pro/farm.config.ts
examples/arco-pro/src/pages/dashboard/monitor/mock/index.ts
packages/cli/src/utils.ts
packages/core/src/compiler/index.ts
packages/core/src/config/constants.ts
packages/core/src/config/env.ts
packages/core/src/config/index.ts
packages/core/src/config/mergeConfig.ts
packages/core/src/config/normalize-config/normalize-asset.ts
packages/core/src/config/normalize-config/normalize-css.ts
packages/core/src/config/normalize-config/normalize-external.ts
packages/core/src/config/normalize-config/normalize-output.ts
packages/core/src/config/normalize-config/normalize-partial-bundling.ts
packages/core/src/config/normalize-config/normalize-resolve.ts
packages/core/src/config/schema.ts
packages/core/src/index.ts
packages/core/src/plugin/index.ts
packages/core/src/plugin/type.ts
packages/core/src/server/index.ts
packages/core/src/watcher/index.ts

chore: optimize node side code

---

.changeset/twelve-radios-hear.md
crates/node/src/plugin_adapters/js_plugin_adapter/hooks/mod.rs
crates/node/src/plugin_adapters/js_plugin_adapter/hooks/process_module.rs
crates/node/src/plugin_adapters/js_plugin_adapter/mod.rs
examples/node-lazy-compile/e2e.spec.ts
examples/node-lazy-compile/farm.config.ts
packages/core/binding/binding.d.ts
packages/core/src/plugin/js/index.ts
packages/core/src/plugin/type.ts
packages/core/src/types/binding.ts

feat: support js process module hook

---

.changeset/spicy-snakes-pay.md
crates/compiler/src/build/module_cache.rs
crates/core/src/cache/cache_store.rs
crates/core/src/cache/module_cache.rs
crates/core/src/cache/module_cache/immutable_modules.rs
crates/core/src/cache/module_cache/mutable_modules.rs
crates/core/src/context/mod.rs
crates/node/src/lib.rs
packages/core/binding/binding.d.ts
packages/core/src/compiler/index.ts

feat: support invalidate module

---

examples/tailwind-next/farm.config.ts
examples/tailwind-next/package.json
examples/tailwind-next/src/App.tsx
examples/tailwind-next/src/index.css
examples/tailwind-next/tailwind.config.js
packages/core/src/server/index.ts
packages/core/src/server/middlewares/resource.ts
packages/core/src/server/middlewares/static.ts
pnpm-lock.yaml

chore: split resource middlewares

---

.changeset/pink-dolls-hug.md
crates/compiler/tests/fixtures/script/import_meta/url/import_meta_url_with_URL/package/.gitignore
crates/compiler/tests/fixtures/script/import_meta/url/import_meta_url_with_URL/package/index.ts
crates/compiler/tests/fixtures/script/import_meta/url/import_meta_url_with_URL/package/node_modules/@foo/core/index.js
crates/compiler/tests/fixtures/script/import_meta/url/import_meta_url_with_URL/package/node_modules/@foo/core/package.json
crates/compiler/tests/fixtures/script/import_meta/url/import_meta_url_with_URL/package/node_modules/bar/index.js
crates/compiler/tests/fixtures/script/import_meta/url/import_meta_url_with_URL/package/node_modules/bar/package.json
crates/compiler/tests/fixtures/script/import_meta/url/import_meta_url_with_URL/package/output.js
crates/plugin_script/src/lib.rs
crates/plugin_script/src/transform_import_meta_url/mod.rs
crates/swc_transformer_import_glob/src/lib.rs
crates/swc_transformer_import_glob/tests/fixtures/no_expr_tpl/dir/bar.js
crates/swc_transformer_import_glob/tests/fixtures/no_expr_tpl/dir/foo.js
crates/swc_transformer_import_glob/tests/fixtures/no_expr_tpl/input.expected.js
crates/swc_transformer_import_glob/tests/fixtures/no_expr_tpl/input.js
crates/swc_transformer_import_glob/tests/mod.rs

```ts
// suport resolve package
import.meta.glob('@foo/core');
new URL('@foo/core', import.meta.url)
import.meta.glob('foo');
new URL('foo', import.meta.url)
// support no expr tpl
import.meta.glob(`./foo.{mjs,ts}`);
```

fix: import.meta.glob support search package

---

examples/arco-pro/farm.config.ts
packages/core/src/config/types.ts
packages/core/src/server/index.ts
pnpm-lock.yaml

chore: add command type in resolvedUserConfig

---

packages/core/src/server/index.ts

fix: fix panic on irrelevant file deletion

---

rust-plugins/replace-dirname/src/lib.rs

chore: optimize `replace_dirname plugin` enhance code robustness

---

packages/core/src/config/index.ts
packages/core/src/index.ts
packages/core/src/plugin/index.ts
packages/core/src/plugin/type.ts
packages/core/src/server/hmr-engine.ts
packages/core/src/server/middlewares/lazyCompilation.ts
packages/core/src/utils/logger.ts
packages/core/src/utils/share.ts
packages/core/src/watcher/index.ts

chore: format time unit

---

.github/workflows/rust-build.yaml
packages/core/src/plugin/js/js-plugin-schema.ts
packages/core/src/plugin/js/utils.ts

fix: updateModules hooks zod type set optional

---

packages/core/src/plugin/js/index.ts

I'm working for visualization plugin, but i found a mistake and it prevent me

fix(core): incorrect schema valiation

---

package.json
rust-plugins/dts/src/lib.rs
scripts/bootstrap.mjs
scripts/build.mjs

fix: build rust plugins scripts add @farmfe/plugin-dts

---

packages/core/src/config/types.ts

docs: update config types annotation

---

packages/core/package.json
pnpm-lock.yaml

chore: remove not exists core dependencies

---

.github/workflows/ci.yaml
.github/workflows/code-spell-check.yaml
.github/workflows/lint.yaml
.github/workflows/release.yaml
.github/workflows/rust-build.yaml
.github/workflows/rust-test.yaml

fix: pnpm version ci error

---

examples/refactor-react/farm.config.ts
packages/core/src/server/middlewares/resource.ts

fix: set `assetsFilename` options get not found resource

---

.changeset/config.json

fix: ignore changeset packages

---

.changeset/long-bulldogs-rule.md
cspell.json
packages/core/src/config/load-config-file.ts

fix: ignore print fileSize in compile config file

---

.changeset/wise-moons-smile.md
packages/runtime/package.json

chore: add src folder with publish runtime packages
