farm-fe/farm

packages/core/src/index.ts

when I write a plugin like this
```js
export deafult function plugin(options):JsPlugin{
return {}
}
```
we maybe need type of 'JsPlugin'

export type of 'JsPlugin'

---

.github/FUNDING.yml
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/PULL_REQUEST_TEMPLATE.md
.github/stale.yml

close: https://github.com/farm-fe/farm/issues/111

feat(template): Add templates for issue and PR

---

.changeset/late-foxes-begin.md
Cargo.lock
crates/core/Cargo.toml
crates/core/src/module/mod.rs

js plugin cannot use custom type
```ts
return {
content: data,
moduleType: 'scss',
}
```
`None`
`None`

fix: js plugin cannot use custom type

---

scripts/build.mjs

Solve the problem that if core is not packaged, it will cause other package build errors.

fix: bootstrap script build core package

---

crates/compiler/examples/react_update.rs
crates/compiler/src/build/mod.rs
crates/compiler/src/update/diff_and_patch_module_graph.rs
crates/compiler/src/update/mod.rs
crates/compiler/src/update/update_context.rs
crates/core/src/module/module_graph.rs
examples/react-antd/src/antd-layout.tsx
examples/react-antd/src/main.tsx
packages/runtime-plugin-hmr/src/hot-module-state.ts
rust-plugins/sass/src/lib.rs

chore: solve issues when add dependencies in HMR

---

js-plugins/vue/package.json
packages/cli/templates/react/package.json
packages/cli/templates/rust-plugin/package.json
packages/cli/templates/vue/package.json
pnpm-lock.yaml
rust-plugins/react/package.json
rust-plugins/sass/package.json

Use pnpm8 to prevent the use of `*` to cause version number inconsistency

fix: pnpm-v8 depsversion error

---

packages/core/src/config/index.ts
packages/core/src/server/index.ts
packages/core/tests/config.spec.ts

This PR forces `server.hmr` option to false for production builds as there is no dev server in those cases anyways. 
Closes #249

feat: disable HMR in prod builds

---

js-plugins/vue/src/generatorCode.ts

A fixed filename is used to generate sfc code, causes same filename in vnode and same component name in Devtools.

fix: sfc filename in @farmfe/js-plugin-vue

---

crates/plugin_css/src/lib.rs
crates/plugin_css/src/transform_resource_pot.rs

plugin css `transform_css_resource_pot` add logic to generate request css file dependency
```css
@import "animate.css";
.test { 
color: red;
}
```
````
//  before:
"src/test.css": function(module, exports, farmRequire, dynamicRequire) {
"use strict";
const cssCode = `.test {
color: red;
}`;
const farmId = "src/test.css";
const previousStyle = document.querySelector(`style[data-farm-id="${farmId}"]`);
const style = document.createElement("style");
style.setAttribute("data-farm-id", farmId);
style.innerHTML = cssCode;
if (previousStyle) {
previousStyle.replaceWith(style);
} else {
document.head.appendChild(style);
}
module.onDispose(()=>{
style.remove();
});
}
// after:
"src/test.css": function(module, exports, farmRequire, dynamicRequire) {
"use strict";
const cssCode = …
```

fix: css import not work

---

.changeset/swift-steaks-cheer.md
.gitignore
examples/vue/package.json
examples/vue/src/Main.vue
examples/vue/src/styles/global.scss
js-plugins/vue/package.json
js-plugins/vue/src/farm-vue-plugin.ts
pnpm-lock.yaml

Fix `@import` syntax in Vue SFC, without fixing, import style should based on root dir
```md
.
├── assets
│   ├── feature.svg
│   ├── light.svg
│   ├── logo.png
│   └── plugin.svg
├── src
│   ├── components
│   │   ├── Button.vue
│   │   ├── Card.vue
│   │   └── Welcome.vue
│   ├── styles
│   │   └── global.scss
│   ├── Main.vue
│   ├── base.css
│   ├── env.d.ts
│   └── index.ts
├── CHANGELOG.md
├── farm.config.ts
├── index.html
├── package.json
└── tsconfig.json
```
Before:
```vue
<script>
// src/Main.vue
</script>
<style lang="less">
// relative path is based on root dir
@import './src/styles/globals.less';
</style>
```
After:
```vue
<script>
// src/Main.vue
</script>
<style lang="less">
// relative path is based on current file dir
@import './styles/globals.less'; …
```

fix: styles import in Vue SFC

---

.changeset/nasty-meals-laugh.md
examples/vue/farm.config.ts
packages/core/src/config/index.ts
packages/core/src/config/schema.ts
packages/core/src/index.ts
packages/core/src/server/index.ts
packages/runtime-plugin-hmr/src/index.ts

Aim: Preventing port conflicts by running an HTTP server to check port availability in advance
See issue #288 / PR #521 for a detailed discussion.

feat: prevent port conflicts

---

.changeset/long-planets-bake.md
packages/core/src/config/index.ts
packages/core/src/server/index.ts

Temporarily resolve websocket port occupancy errors due to host inconsistencies
The next step is to solve the problem of websocket and http sharing a set of ports.

fix: Temporarily resolve websocket port occupancy errors due to host inconsistencies

---

packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/server/middlewares/hmr.ts
packages/runtime-plugin-hmr/src/index.ts

when `hmr.host` & `hmr.port` is same as dev server, reuse the dev server to handle hmr request.
if reuse_mode, ws server need a unique path, so add a new property  `config.server.hmr.path`. the default value is '__hmr'
```ts
//server.hmr
{
path?:string; //default: '__hmr'
}
```
#545

feat: reuse http server when hmr is not configured

---

.changeset/fuzzy-bats-jump.md
examples/less/farm.config.ts
js-plugins/less/src/index.ts

When the additionalData function return nothing, the less api will complie `undefined`,it is illegal.
None
None

fix: avoid the situation where the return value of additionalData is not a string

---

.changeset/late-emus-wait.md
crates/compiler/src/generate/render_resource_pots.rs

Expect:
```css
/*# sourceMappingURL=/assets/multi-dimension-data-analysis_index_54e1.265a4b83.css.map */
```
Current:
```css
//# sourceMappingURL=/assets/multi-dimension-data-analysis_index_54e1.265a4b83.css.map
```
Step:
1. `git clone git@github.com:farm-fe/farm.git`
2. `cd examples/arco-pro`
3. `pnpm run build`
4. see `build/assets/*.css`

fix: css resource cannot find sourcemap

---

.changeset/perfect-suits-lie.md
.vscode/settings.json
packages/core/src/utils/build.ts
packages/core/src/utils/color.ts
packages/create-farm/index.ts
packages/create-farm/package.json
packages/create-farm/templates/react/package.json
packages/create-farm/templates/solid/package.json
packages/create-farm/templates/vue/package.json
packages/create-farm/utils/color.ts
packages/create-farm/utils/gradient.ts
pnpm-lock.yaml

optimize(create-farm): Remove child process log output remove chalk library optimize code size

---

packages/core/src/watcher/configWatcher.ts

fix: Avoid passing `null | undefined` values into JsWatcher

---

.changeset/gentle-gorillas-agree.md
crates/core/src/cache/cache_store.rs
crates/plugin_css/src/transform_css_to_script.rs
crates/plugin_runtime/src/render_resource_pot/mod.rs
examples/vite-adapter-vue/farm.config.ts
examples/vite-adapter-vue/src/components/Intro.vue

fix persistent cache conflicts introduced by https://github.com/farm-fe/farm/commit/b1a5b8dd509a00a27764a8bc0a7cf43c90ae0274

fix: persistent cache conflicts

---

.changeset/nine-schools-visit.md
packages/core/src/config/index.ts
packages/core/src/plugin/js/farm-to-vite-config.ts
packages/core/src/utils/plugin-utils.ts

…, resulting in errors
当某些`vite config` 没有配置`resolve?.alias`的时候为`undefined`会导致出现`resolve?.alias.some is not function`不能正常启动服务。
可以使用[vite-adapter-vue2.7](https://github.com/farm-fe/farm/tree/main/examples/vite-adapter-vue2.7)项目进行复现。
将[farm config L7-L15配置](https://github.com/farm-fe/farm/blob/main/examples/vite-adapter-vue2.7/farm.config.ts#L7-L15)移除。
这里提供一个默认值避免获取`resolve?.alias`的时候为`undefined`。
这里给vite config 提供一个`Alias[]`数组(空数组）,目前这样配置可以正常启动服务，

fix(vite plugin): some vite plugins do not provide alias configuration errors

---

.changeset/spotty-shrimps-teach.md
crates/plugin_runtime/src/handle_entry_resources.rs
crates/plugin_runtime/src/lib.rs
packages/core/src/config/index.ts

- better error tip
- external inject logic
external maybe from external
```ts
export function autoExternal(): JsPlugin {
return {
priority: -Infinity,
name: `${CLI_NAME}:AutoExternal`,
resolve: {
filters: {
sources: ['.*'],
importers: ['.*'],
},
async executor(param): Promise<PluginResolveHookResult> {
logger.debug(`${param.source} not found, it to be set external`);
return {
resolvedPath: param.source,
external: true,
};
},
},
};
}
```

fix: external inject logic

---

.changeset/serious-bears-grin.md
Cargo.lock
crates/create-farm-rs/Cargo.toml
crates/create-farm-rs/src/args.rs
crates/create-farm-rs/src/lib.rs
crates/create-farm-rs/src/package_manager.rs
crates/create-farm-rs/src/template.rs

- Use `clap` instead of `pico-args` to parse args
- Use `clap` to implement cli helper
- Fix all warnings of dead codes
- Fix `--manager` takes no effect
- Update dependencies and remove `pico-args`
**Looks Like:**
**Related issue:** #1277

refactor(create-farm): rewrite `create-farm` with `clap`

---

packages/core/src/server/index.ts
packages/core/src/utils/cacheDir.ts
packages/core/src/utils/index.ts
packages/core/src/utils/logger.ts
packages/core/src/watcher/create-watcher.ts

cacheDir check for the FILLEXTREME logger
#1589

feat: cacheDir check for the FILLEXTREME

---

.changeset/weak-dogs-lie.md
crates/core/src/config/css.rs
crates/core/src/config/custom.rs
crates/core/src/config/mod.rs
crates/core/src/lib.rs
crates/plugin_css/src/lib.rs
cspell.json
packages/core/src/config/constants.ts
packages/core/src/config/index.ts
packages/core/src/config/normalize-config/normalize-css.ts
packages/core/src/config/schema.ts
packages/core/src/config/types.ts
packages/core/src/types/binding.ts

```ts
defineConfig({
compilation: {
css: {
modules: {
localsConversion: 'lowerCamel'
}
},
}
})
```
close #1367

feat(css): support css module name coversion

---

.changeset/short-roses-dream.md
crates/toolkit/src/fs/mod.rs
crates/toolkit/tests/fixtures/script/index.js
crates/toolkit/tests/fixtures/script/index.jsx
crates/toolkit/tests/fixtures/script/index.ts
crates/toolkit/tests/fixtures/script/index.tsx

When the user file content appears to be illegal utf8, the current error exception is not friendly. At the same time we should not throw such exceptions to developers
None
None

fix: ignore non-utf8 error when getting file contents

---

.changeset/loud-dogs-double.md
.vscode/settings.json
examples/refactor-react/base.html
examples/refactor-react/farm.config.ts
packages/core/src/config/index.ts
packages/core/src/config/schema.ts
packages/core/src/config/types.ts
packages/core/src/server/index.ts
packages/core/src/server/middlewares/htmlFallback.ts
packages/core/src/server/middlewares/resource.ts
packages/core/src/utils/plugin-utils.ts
scripts/build.mjs

Integrating farm dev server has `all middleware` functions and the impact of `appType` on configuring `spa`, `mpa` and `custom` fields functions
The following is a brief explanation of the core points of this pr, only about the appType function
The functions of each part of the middleware in the following order are as follows
- corsMiddleware: Allowing the server to control which cross-domain requests can be accepted by the browser
- proxyMiddleware: Mainly used to process proxy requests in the development server
- publicPathMiddleware: Routing control to be used to handle static resource and URL redirects
- adapterViteMiddleware: A middleware used to process resource files in Vite development mode. Its main purpose is to ensure that certain resources (such as images or fonts) are …

chore(v2): Integrate middleware and htmlfallback middlewear usage

---

.changeset/good-pants-repair.md
.changeset/strong-scissors-reply.md
crates/compiler/tests/fixtures/tree_shake/deep_dynamic_import/output.js
crates/plugin_runtime/src/render_resource_pot/transform_async_module.rs
e2e/vitestSetup.ts
examples/tree-shake-antd/e2e.spec.ts
packages/core/src/plugin/js/vite-plugin-adapter.ts

fix: wrong esm introp helper order when using top level await

---

crates/compiler/src/lib.rs
crates/core/src/module/module_graph.rs
crates/core/src/plugin/plugin_driver.rs

I'm building framework around farm that requires "sub-build"s. The main problem blocking me from achieving this is the inability to access the plugins from the current compiler context/plugin driver.
With these changes, I am able to create a sub-compiler to create a sub-build like this:
```
fn load(
&self,
param: &PluginLoadHookParam,
context: &Arc<CompilationContext>,
hook_context: &PluginHookContext,
) -> Result<Option<PluginLoadHookResult>> {
let mut config = context.config.as_ref().clone();
config.progress = false;
config.input = HashMap::new();
config.input.insert(String::from("client"), "anothermodule.ts");
let compiler =
Compiler::new_without_internal_plugins(config, context.plugin_driver.plugins.clone())?;
// copy module graph to new compiler
context
.module_graph …
```

feat(plugins): add primitives to support sub-compiler usage

---

examples/vue3/farm.config.ts
examples/vue3/package.json
examples/vue3/src/index.ts
package.json
packages/core/src/config/schema.ts
pnpm-lock.yaml
scripts/build.mjs
scripts/logger.mjs

- 1. @farm/cli cli type 
CLI types include global general instruction types, start types, build types, and preview types
- 2. @farmfe/core defineConfig  
defineConfig type include
1. Basic types: Basic types mainly provide edge functions for nodes, such as base, logger, 
2. Compilation types: It mainly contains all types that need to be passed to rust on the node side
- 3. @farmfe/core jsplugin Reorganize js plugin types

refactor(v2): optimize scripts code 

---

README.md

Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Farm Guru](https://gurubase.io/g/farm) to Gurubase. Farm Guru uses the data from this repo and data from the [docs](https://farmfe.org) to answer questions by leveraging the LLM.
In this PR, I showcased the "Farm Guru", which highlights that Farm now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want me to disable Farm Guru …

Introducing Farm Guru on Gurubase.io

---

packages/core/src/utils/path.ts

The original code uses `path.posix.relative()` that specifics the platform to linux, use `path.relative` to automaically determine how to extract the relative path.
Resolved: #1859

fix: short name display on windows

---

.changeset/hungry-bikes-guess.md
crates/plugin_html/src/resources_injector.rs
examples/react/farm.config.js

if runtime.isolate was set to be true , `global_this` or `initial_loaded_resources` will set to be external  
None
https://github.com/farm-fe/farm/issues/1803

fix: disable inline scripts

---

packages/core/src/config/schema.ts
packages/core/src/server/index.ts
packages/core/src/server/middlewares/htmlFallback.ts
packages/core/src/server/middlewares/lazyCompilation.ts
packages/core/src/server/middlewares/proxy.ts
packages/core/src/server/middlewares/resource.ts
packages/core/src/server/middlewares/static.ts
packages/core/src/server/preview.ts
packages/core/src/server/ws.ts

chore: Add origin schema and optimize server resolvedUserconfig renaming

---

.changeset/dull-carrots-think.md
crates/compiler/src/update/handle_update_modules.rs
crates/compiler/src/update/mod.rs
js-plugins/postcss/package.json

fix accidental remove of modules in `watch graph`
fix #2024

fix: do not clean up then watch graph monitoring module

---

examples/vue3/farm.config.ts
examples/vue3/package.json
examples/vue3/src/App.vue
packages/core/src/config/index.ts
packages/core/src/config/types.ts
packages/core/src/plugin/js/js-plugin-schema.ts
packages/core/src/plugin/js/vite-plugin-adapter.ts
packages/core/src/plugin/type.ts
packages/core/src/server/hmr-engine.ts
pnpm-lock.yaml

chore: add context parameters to updateModules hook

---

.changeset/forty-tips-jump.md
crates/create-farm-rs/templates/react/src/index.tsx
crates/create-farm-rs/templates/react/src/main.tsx

**Description:** after use the `pnpm create farm` create the react template, the template code has some warning.
**BREAKING CHANGE:** no
**Related issue (if exists):** no

chore: delete react template warning code

---

.changeset/tiny-berries-think.md
crates/plugin_resolve/src/lib.rs

* When I externalize dependencies with querystring, the query duplicates.
* For example:
* `import { Astal } from 'gi://Astal?version=4.0`
* with externalizing `['^gi://']`
* yields `import { o } from "gi://Astal?version=4.0?version=4.0";`
**Reproduction:**
<details>
```diff
diff --git a/farm.config.js b/farm.config.js
new file mode 100644
index 0000000..aaa84db
--- /dev/null
+++ b/farm.config.js
@@ -0,0 +1,9 @@
+import { defineConfig } from '@farmfe/core';
+
+export default defineConfig({
+	compilation: {
+		input: { index: './index.js' },
+		output: { targetEnv: 'library' },
+		external: ['^gi://']
+	},
+});
diff --git a/index.js b/index.js
new file mode 100644
index 0000000..0c019aa
--- /dev/null
+++ b/index.js
@@ -0,0 +1,2 @@
+import Astal from …
```

fix(plugin_resolve): duplicated querystring on external

---

examples/refactor-react/farm.config.ts
rust-plugins/replace-dirname/src/lib.rs

Recursive processing is required when `chain calls` to object expressions `visit_mut_expr` processing `__dirname` and more

fix: #2062

---

examples/arco-pro/e2e.spec.ts
packages/core/src/server/index.ts
packages/core/src/utils/http.ts

chore: print network url by default

---

.changeset/giant-apples-invite.md
crates/compiler/src/generate/render_resource_pots.rs
examples/arco-pro/farm.config.ts

Delete useless map file when config is 'inline'

fix: delete map file when conifg is 'inline' or 'all-inline'
